/*
 * Reading support for long-form Japanese content. The Japanese text remains
 * canonical; these readings are a separate, reviewable layer so missing or
 * machine-generated support cannot silently become medical terminology.
 */

export type JapaneseReading = { kana: string; romaji: string };

export const JAPANESE_READINGS: Record<string, JapaneseReading> = {
  "10段階だと8くらいです。今も続いています。": { kana: "10だんかいだと8くらいです。いまもつづいています。", romaji: "10 dankai da to 8 kurai desu。 ima mo tsuzui te i masu。" },
  "1か月くらい前から水をよく飲むようになり、体重が4キロ減りました。": { kana: "1かげつくらいまえからみずをよくのむようになり、たいじゅうが4きろへりました。", romaji: "1 kagetsu kurai mae kara mizu o yoku nomu yoo ni nari、 taijuu ga 4 kiro heri mashi ta。" },
  "1か月で4キロ減りました。特に食事は変えていません。": { kana: "1かげつで4きろへりました。とくにしょくじはかえていません。", romaji: "1 kagetsu de 4 kiro heri mashi ta。 tokuni shokuji wa kae te i mase n。" },
  "1時間前、朝食中に急に右手が動かなくなりました。": { kana: "1じかんまえ、ちょうしょくちゅうにきゅうにみぎてがうごかなくなりました。", romaji: "1 jikan mae、 chooshoku chuu ni kyuu ni migite ga ugoka naku nari mashi ta。" },
  "2分くらいだったと思います。時計を見ていました。": { kana: "2ふんくらいだったとおもいます。とけいをみていました。", romaji: "2 fun kurai datsu ta to omoi masu。 tokee o mi te i mashi ta。" },
  "2回吐きました。食欲がありません。": { kana: "2かいはきました。しょくよくがありません。", romaji: "2 kai haki mashi ta。 shokuyoku ga ari mase n。" },
  "37.8度くらいあります。": { kana: "37.8どくらいあります。", romaji: "37. 8 do kurai ari masu。" },
  "3日前からです。だんだん悪くなっています。": { kana: "3かまえからです。だんだんわるくなっています。", romaji: "3 ka mae kara desu。 dandan waruku natsu te i masu。" },
  "3日前から熱が出て、咳と痰が止まりません。": { kana: "3かまえからねつがでて、せきとたんがとまりません。", romaji: "3 ka mae kara netsu ga de te、 seki to tan ga tomari mase n。" },
  "7時ごろ、箸を落として気づきました。": { kana: "7じごろ、はしをおとしてきづきました。", romaji: "7 ji goro、 hashi o otoshi te kizuki mashi ta。" },
  "A型とだけ言われました。Rhは分かりません。": { kana: "Aがたとだけいわれました。Rhはわかりません。", romaji: "A gata to dake iwa re mashi ta。 Rh wa wakari mase n。" },
  "COPDと言われています。あと、以前腰の手術をしました。": { kana: "COPDといわれています。あと、いぜんこしのしゅじゅつをしました。", romaji: "COPD to iwa re te i masu。 ato、 izen koshi no shujutsu o shi mashi ta。" },
  "Rhの型は分かりますか": { kana: "Rhのかたはわかりますか", romaji: "Rh no kata wa wakari masu ka" },
  "いつからですか": { kana: "いつからですか", romaji: "itsu kara desu ka" },
  "いつから動悸がしますか": { kana: "いつからどうきがしますか", romaji: "itsu kara dooki ga shi masu ka" },
  "いつから様子が変わりましたか": { kana: "いつからようすがかわりましたか", romaji: "itsu kara yoosu ga kawari mashi ta ka" },
  "いつから熱がありますか": { kana: "いつからねつがありますか", romaji: "itsu kara netsu ga ari masu ka" },
  "いつから症状が出ましたか": { kana: "いつからしょうじょうがでましたか", romaji: "itsu kara shoojoo ga de mashi ta ka" },
  "いつから痛みますか": { kana: "いつからいたみますか", romaji: "itsu kara itami masu ka" },
  "おしっこの調子は悪くないですか": { kana: "おしっこのちょうしはわるくないですか", romaji: "oshikko no chooshi wa waruku nai desu ka" },
  "おしっこは出ていますか": { kana: "おしっこはでていますか", romaji: "oshikko wa de te i masu ka" },
  "おしっこは普通です。痛くありません。": { kana: "おしっこはふつうです。いたくありません。", romaji: "oshikko wa futsuu desu。 itaku ari mase n。" },
  "おなかが痛い": { kana: "おなかがいたい", romaji: "onaka ga itai" },
  "おなかを触ると嫌がりますか": { kana: "おなかをさわるといやがりますか", romaji: "onaka o sawaru to iya gari masu ka" },
  "おなかを触ると顔をしかめます。右側を嫌がります。": { kana: "おなかをさわるとかおをしかめます。みぎがわをいやがります。", romaji: "onaka o sawaru to kao o shikame masu。 migigawa o iya gari masu。" },
  "おりものシートにつくくらいです。増えてはいません。": { kana: "おりものしーとにつくくらいです。ふえてはいません。", romaji: "orimono shiito ni tsuku kurai desu。 fue te wa i mase n。" },
  "お薬手帳はありますか": { kana: "おくすりてちょうはありますか", romaji: "o kusuri techoo wa ari masu ka" },
  "お薬手帳はお持ちですか": { kana: "おくすりてちょうはおもちですか", romaji: "o kusuri techoo wa o mochi desu ka" },
  "お薬手帳を持ってきました。先月、抗菌薬を飲んだと書いてあります。": { kana: "おくすりてちょうをもってきました。せんげつ、こうきんやくをのんだとかいてあります。", romaji: "o kusuri techoo o motsu te ki mashi ta。 sengetsu、 kookin yaku o non da to kai te ari masu。" },
  "お酒は飲みますか": { kana: "おさけはのみますか", romaji: "o sake wa nomi masu ka" },
  "けいれんと発熱": { kana: "けいれんとはつねつ", romaji: "keeren to hatsunetsu" },
  "けいれんの後、意識は戻りましたか": { kana: "けいれんのあと、いしきはもどりましたか", romaji: "keeren no ato、 ishiki wa modori mashi ta ka" },
  "けいれんはどのくらい続きましたか": { kana: "けいれんはどのくらいつづきましたか", romaji: "keeren wa dono kurai tsuzuki mashi ta ka" },
  "けいれんは繰り返しましたか": { kana: "けいれんはくりかえしましたか", romaji: "keeren wa kurikaeshi mashi ta ka" },
  "この問題に対して、訪問診療の拡大が進められてきた。医師が自宅を訪れることで通院の負担は減る。しかし、訪問診療だけで急性期の対応ができるわけではない。肺炎や心筋梗塞のような緊急の状態では、やはり病院の機能が必要である。": { kana: "このもんだいにたいして、ほうもんしんりょうのかくだいがすすめられてきた。いしがじたくをおとずれることでつういんのふたんはへる。しかし、ほうもんしんりょうだけできゅうせいきのたいおうができるわけではない。はいえんやしんきんこうそくのようなきんきゅうのじょうたいでは、やはりびょういんのきのうがひつようである。", romaji: "kono mondai ni taishi te、 hoomon shinryoo no kakudai ga susume rare te ki ta。 ishi ga jitaku o otozureru koto de tsuuin no futan wa heru。 shikashi、 hoomon shinryoo dake de kyuusee ki no taioo ga dekiru wake de wa nai。 haien ya shinkin koosoku no yoo na kinkyuu no jootai de wa、 yahari byooin no kinoo ga hitsuyoo de aru。" },
  "ご不便をおかけしますが、ご理解のほどよろしくお願いいたします。": { kana: "ごふべんをおかけしますが、ごりかいのほどよろしくおねがいいたします。", romaji: "go fuben o o kake shi masu ga、 go rikai no hodo yoroshiku o negai itashi masu。" },
  "ご予約の変更が必要な方は、3月25日までに受付またはお電話でご連絡ください。この期日を過ぎますと、4月以降のご予約は新しい診療時間での調整となります。オンラインでの変更も可能ですが、初めてご利用の方は受付での手続きが必要です。": { kana: "ごよやくのへんこうがひつようなかたは、3がつ25かまでにうけつけまたはおでんわでごれんらくください。このきじつをすぎますと、4がついこうのごよやくはあたらしいしんりょうじかんでのちょうせいとなります。おんらいんでのへんこうもかのうですが、はじめてごりようのほうはうけつけでのてつづきがひつようです。", romaji: "go yoyaku no henkoo ga hitsuyoo na kata wa、 3 gatsu 25 ka made ni uketsuke mata wa o denwa de go renraku kudasai。 kono kijitsu o sugi masu to、 4 gatsu ikoo no go yoyaku wa atarashii shinryoo jikan de no choosee to nari masu。 on rain de no henkoo mo kanoo desu ga、 hajimete go riyoo no hoo wa uketsuke de no tetsuzuki ga hitsuyoo desu。" },
  "ご家族にけいれんの方はいますか": { kana: "ごかぞくにけいれんのほうはいますか", romaji: "go kazoku ni keeren no hoo wa i masu ka" },
  "ご家族に心臓の病気の方はいますか": { kana: "ごかぞくにしんぞうのびょうきのほうはいますか", romaji: "go kazoku ni shinzoo no byooki no hoo wa i masu ka" },
  "ご家族に糖尿病の方はいますか": { kana: "ごかぞくにとうにょうびょうのほうはいますか", romaji: "go kazoku ni toonyoo byoo no hoo wa i masu ka" },
  "ご家族に連絡してもいいですか": { kana: "ごかぞくにれんらくしてもいいですか", romaji: "go kazoku ni renraku shi te mo ii desu ka" },
  "ご都合が悪い場合は、明日の午前中までにご返信いただけますと助かります。ご確認のほど、よろしくお願いいたします。": { kana: "ごつごうがわるいばあいは、あすのごぜんちゅうまでにごへんしんいただけますとたすかります。ごかくにんのほど、よろしくおねがいいたします。", romaji: "go tsugoo ga warui baai wa、 asu no gozen chuu made ni go henshin itadake masu to tasukari masu。 go kakunin no hodo、 yoroshiku o negai itashi masu。" },
  "しかし、この考え方には見直しが迫られている。効果が測定できる以上、それはノイズではなく、意味のある反応である。脳の活動や免疫の指標が実際に変化することが報告されている。": { kana: "しかし、このかんがえかたにはみなおしがせまられている。こうかがそくていできるいじょう、それはのいずではなく、いみのあるはんのうである。のうのかつどうやめんえきのしひょうがじっさいにへんかすることがほうこくされている。", romaji: "shikashi、 kono kangae kata ni wa minaoshi ga semara re te iru。 kooka ga sokutee dekiru ijoo、 sore wa noizu de wa naku、 imi no aru hannoo de aru。 noo no katsudoo ya men'eki no shihyoo ga jissai ni henka suru koto ga hookoku sa re te iru。" },
  "しかし、在宅勤務を手放しで評価することはできない。同僚と顔を合わせる機会が減ると、ちょっとした相談がしにくくなる。結果として、若い社員が仕事の進め方を学ぶ機会が失われているという指摘もある。": { kana: "しかし、ざいたくきんむをてばなしでひょうかすることはできない。どうりょうとかおをあわせるきかいがへると、ちょっとしたそうだんがしにくくなる。けっかとして、わかいしゃいんがしごとのすすめかたをまなぶきかいがうしなわれているというしてきもある。", romaji: "shikashi、 zaitaku kinmu o tebanashi de hyooka suru koto wa deki nai。 dooryoo to kao o awaseru kikai ga heru to、 chotto shi ta soodan ga shi nikuku naru。 kekka to shi te、 wakai shain ga shigoto no susume kata o manabu kikai ga ushinawa re te iru to yuu shiteki mo aru。" },
  "したがって、必要なのは訪問でも病院でもどちらか一方を選ぶことではなく、状態の変化に応じて両者を組み合わせる仕組みである。往診から入院への移行が円滑に進むかどうかが、地域医療の質を左右する。": { kana: "したがって、ひつようなのはほうもんでもびょういんでもどちらかいっぽうをえらぶことではなく、じょうたいのへんかにおうじてりょうしゃをくみあわせるしくみである。おうしんからにゅういんへのいこうがえんかつにすすむかどうかが、ちいきいりょうのしつをさゆうする。", romaji: "shitagatsu te、 hitsuyoo na no wa hoomon de mo byooin de mo dochira ka ippoo o erabu koto de wa naku、 jootai no henka ni ooji te ryoosha o kumiawaseru shikumi de aru。 ooshin kara nyuuin e no ikoo ga enkatsu ni susumu ka doo ka ga、 chiiki iryoo no shitsu o sayuu suru。" },
  "しびれはありますか": { kana: "しびれはありますか", romaji: "shibire wa ari masu ka" },
  "ずっと続いています。時々治まる感じもしません。": { kana: "ずっとつづいています。ときどきおさまるかんじもしません。", romaji: "zutto tsuzui te i masu。 tokidoki osamaru kanji mo shi mase n。" },
  "ずっと続いていますか": { kana: "ずっとつづいていますか", romaji: "zutto tsuzui te i masu ka" },
  "そういう症状はありません。": { kana: "そういうしょうじょうはありません。", romaji: "soo yuu shoojoo wa ari mase n。" },
  "そのためには、日頃から顔の見える関係が作られている必要がある。紹介状一通で連携できるかどうかは、制度よりも、その前に交わされた会話の積み重ねによって決まる。": { kana: "そのためには、ひごろからかおのみえるかんけいがつくられているひつようがある。しょうかいじょういちつうでれんけいできるかどうかは、せいどよりも、そのまえにかわされたかいわのつみかさねによってきまる。", romaji: "sono tame ni wa、 higoro kara kao no mieru kankee ga tsukura re te iru hitsuyoo ga aru。 shookai joo ichi tsuu de renkee dekiru ka doo ka wa、 seedo yori mo、 sono mae ni kawasa re ta kaiwa no tsumikasane ni yotsu te kimaru。" },
  "その後どうなりましたか": { kana: "そのあとどうなりましたか", romaji: "sono ato doo nari mashi ta ka" },
  "そばを食べました。20分くらい後です。": { kana: "そばをたべました。20ふんくらいあとです。", romaji: "soba o tabe mashi ta。 20 fun kurai ato desu。" },
  "ただし、特定の細菌を増やせば病気にならない、という単純な話ではない。菌の種類によって働きは異なり、同じ菌でも宿主の状態によって結果が変わることもある。因果関係と相関関係を混同しないことが、この分野では特に重要である。": { kana: "ただし、とくていのさいきんをふやせばびょうきにならない、というたんじゅんなはなしではない。きんのしゅるいによってはたらきはことなり、おなじきんでもしゅくしゅのじょうたいによってけっかがかわることもある。いんがかんけいとそうかんかんけいをこんどうしないことが、このぶんやではとくにじゅうようである。", romaji: "tadashi、 tokutee no saikin o fuyase ba byooki ni nara nai、 to yuu tanjun na hanashi de wa nai。 kin no shurui ni yotsu te hataraki wa kotonari、 onaji kin de mo shukushu no jootai ni yotsu te kekka ga kawaru koto mo aru。 inga kankee to sookan kankee o kondoo shi nai koto ga、 kono bunya de wa tokuni juuyoo de aru。" },
  "たとえば、無菌の状態で育てた動物は、通常の動物に比べて免疫の機能が弱いことが知られている。腸内細菌が、免疫細胞の訓練に関わっていると考えられるゆえんである。": { kana: "たとえば、むきんのじょうたいでそだてたどうぶつは、つうじょうのどうぶつにくらべてめんえきのきのうがよわいことがしられている。ちょうないさいきんが、めんえきさいぼうのくんれんにかかわっているとかんがえられるゆえんである。", romaji: "tatoeba、 mukin no jootai de sodate ta doobutsu wa、 tsuujoo no doobutsu ni kurabe te men'eki no kinoo ga yowai koto ga shira re te iru。 choonai saikin ga、 men'eki saiboo no kunren ni kakawatsu te iru to kangae rareru yuen de aru。" },
  "たとえば、説明の仕方や診察の時間そのものが症状の変化に影響することが知られている。これを「効果のない治療を勧めてよい理由」と取り違えないことが重要である。": { kana: "たとえば、せつめいのしかたやしんさつのじかんそのものがしょうじょうのへんかにえいきょうすることがしられている。これを「こうかのないちりょうをすすめてよいりゆう」ととりちがえないことがじゅうようである。", romaji: "tatoeba、 setsumee no shikata ya shinsatsu no jikan sono mono ga shoojoo no henka ni eekyoo suru koto ga shira re te iru。 kore o「 kooka no nai chiryoo o susume te yoi riyuu」 to torichigae nai koto ga juuyoo de aru。" },
  "とはいえ、出社を全員に求めることが解決策になるわけでもない。通勤に1時間以上かかる人にとって、毎日の出社は負担が大きい。大事なのは、在宅と出社のどちらが優れているかを決めることではなく、仕事の性質に応じて選べるようにすることである。": { kana: "とはいえ、しゅっしゃをぜんいんにもとめることがかいけつさくになるわけでもない。つうきんに1じかんいじょうかかるひとにとって、まいにちのしゅっしゃはふたんがおおきい。だいじなのは、ざいたくとしゅっしゃのどちらがすぐれているかをきめることではなく、しごとのせいしつにおうじてえらべるようにすることである。", romaji: "to wa ie、 shussha o zen'in ni motomeru koto ga kaiketsu saku ni naru wake de mo nai。 tsuukin ni 1 jikan ijoo kakaru hito ni totsu te、 mainichi no shussha wa futan ga ookii。 daiji na no wa、 zaitaku to shussha no dochira ga sugure te iru ka o kimeru koto de wa naku、 shigoto no seeshitsu ni ooji te eraberu yoo ni suru koto de aru。" },
  "どこが痛いですか": { kana: "どこがいたいですか", romaji: "doko ga itai desu ka" },
  "どこに広がりますか": { kana: "どこにひろがりますか", romaji: "doko ni hirogari masu ka" },
  "どのくらいの時間でしたか": { kana: "どのくらいのじかんでしたか", romaji: "dono kurai no jikan deshi ta ka" },
  "どのくらい痛いですか": { kana: "どのくらいいたいですか", romaji: "dono kurai itai desu ka" },
  "どのくらい続きますか": { kana: "どのくらいつづきますか", romaji: "dono kurai tsuzuki masu ka" },
  "どのような痛みですか": { kana: "どのようないたみですか", romaji: "dono yoo na itami desu ka" },
  "どんな痛みですか": { kana: "どんないたみですか", romaji: "donna itami desu ka" },
  "なお、土曜日の午後は救急外来のみの対応となります。緊急の場合は、事前の予約なしで受診していただけますが、救急外来の混雑状況によって待ち時間が長くなることがあります。": { kana: "なお、どようひのごごはきゅうきゅうがいらいのみのたいおうとなります。きんきゅうのばあいは、じぜんのよやくなしでじゅしんしていただけますが、きゅうきゅうがいらいのこんざつじょうきょうによってまちじかんがながくなることがあります。", romaji: "nao、 doyoo hi no gogo wa kyuukyuu gairai nomi no taioo to nari masu。 kinkyuu no baai wa、 jizen no yoyaku nashi de jushin shi te itadake masu ga、 kyuukyuu gairai no konzatsu jookyoo ni yotsu te machi jikan ga nagaku naru koto ga ari masu。" },
  "なお、当日は検査機器の納品が入っており、14時台は会議室の前の通路が混み合う見込みです。16時以降であれば、その混雑も落ち着いていると考えられます。部長にご出席いただく資料は、前日までにメールでお送りいたします。": { kana: "なお、とうじつはけんさききののうひんがはいっており、14じだいはかいぎしつのまえのつうろがこみあうみこみです。16じいこうであれば、そのこんざつもおちついているとかんがえられます。ぶちょうにごしゅっせきいただくしりょうは、ぜんじつまでにめーるでおおくりいたします。", romaji: "nao、 toojitsu wa kensa kiki no noohin ga haitsu te ori、 14 ji dai wa kaigi shitsu no mae no tsuuro ga komiau mikomi desu。 16 ji ikoo de are ba、 sono konzatsu mo ochitsui te iru to kangae rare masu。 buchoo ni go shusseki itadaku shiryoo wa、 zenjitsu made ni meeru de o okuri itashi masu。" },
  "にもかかわらず、説明の評価は伝えた内容で測られがちである。記録に残るのは「何を話したか」であり、「相手に何が起きたか」ではない。ここに、説明が十分に行われたと双方が思い込む余地が生まれる。": { kana: "にもかかわらず、せつめいのひょうかはつたえたないようではかられがちである。きろくにのこるのは「なんをはなしたか」であり、「あいてになんがおきたか」ではない。ここに、せつめいがじゅうぶんにおこなわれたとそうほうがおもいこむよちがうまれる。", romaji: "ni mo kakawara zu、 setsumee no hyooka wa tsutae ta naiyoo de hakara re gachi de aru。 kiroku ni nokoru no wa「 nan o hanashi ta ka」 de ari、「 aite ni nan ga oki ta ka」 de wa nai。 koko ni、 setsumee ga juubun ni okonawa re ta to soohoo ga omoikomu yochi ga umareru。" },
  "のどが腫れている感じはありますか": { kana: "のどがはれているかんじはありますか", romaji: "nodo ga hare te iru kanji wa ari masu ka" },
  "のどが詰まる感じで、声が出しにくいです。": { kana: "のどがつまるかんじで、こえがだしにくいです。", romaji: "nodo ga tsumaru kanji de、 koe ga dashi nikui desu。" },
  "のどの渇きと体重減少": { kana: "のどのかわきとたいじゅうげんしょう", romaji: "nodo no kawaki to taijuu genshoo" },
  "のどは渇きますか": { kana: "のどはかわきますか", romaji: "nodo wa kawaki masu ka" },
  "ふだんは会話できますか": { kana: "ふだんはかいわできますか", romaji: "fudan wa kaiwa deki masu ka" },
  "ふらつきはありません。肩の痛みもありません。": { kana: "ふらつきはありません。かたのいたみもありません。", romaji: "furatsuki wa ari mase n。 kata no itami mo ari mase n。" },
  "ふらつきや気を失う感じはありますか": { kana: "ふらつきやきをうしなうかんじはありますか", romaji: "furatsuki ya ki o ushinau kanji wa ari masu ka" },
  "アドレナリンを持っていますか": { kana: "あどれなりんをもっていますか", romaji: "adorenarin o motsu te i masu ka" },
  "ゼーゼーして、息が吸いにくいです。": { kana: "ぜーぜーして、いきがすいにくいです。", romaji: "zeezee shi te、 iki ga sui nikui desu。" },
  "ゼーゼーしますか": { kana: "ぜーぜーしますか", romaji: "zeezee shi masu ka" },
  "タバコは吸いますか": { kana: "たばこはすいますか", romaji: "tabako wa sui masu ka" },
  "トイレの回数は増えましたか": { kana: "といれのかいすうはふえましたか", romaji: "toire no kaisuu wa fue mashi ta ka" },
  "プラセボ効果とは、薬理作用のない処置でも症状が改善する現象を指す。長い間、これは臨床試験における「ノイズ」として扱われ、できるだけ取り除くべきものとされてきた。": { kana: "ぷらせぼこうかとは、やくりさようのないしょちでもしょうじょうがかいぜんするげんしょうをさす。ながいあいだ、これはりんしょうしけんにおける「のいず」としてあつかわれ、できるだけとりのぞくべきものとされてきた。", romaji: "purasebo kooka to wa、 yakuri sayoo no nai shochi de mo shoojoo ga kaizen suru genshoo o sasu。 nagai aida、 kore wa rinshoo shiken ni oke ru「 noizu」 to shi te atsukawa re、 dekiru dake torinozoku beki mono to sa re te ki ta。" },
  "一方で、眠れない日が続いても、それを気にするあまり床の上で長い時間を過ごすのは逆効果になりかねない。眠れないときは一度床を離れ、暗い部屋で静かに過ごすほうがよいとされている。": { kana: "いっぽうで、ねむれないひがつづいても、それをきにするあまりゆかのうえでながいじかんをすごすのはぎゃくこうかになりかねない。ねむれないときはいちどゆかをはなれ、くらいへやでしずかにすごすほうがよいとされている。", romaji: "ippoo de、 nemure nai hi ga tsuzui te mo、 sore o ki ni suru amari yuka no ue de nagai jikan o sugosu no wa gyaku kooka ni nari kane nai。 nemure nai toki wa ichi do yuka o hanare、 kurai heya de shizuka ni sugosu hoo ga yoi to sa re te iru。" },
  "下腹部が重い感じで、ずきずきはしません。急に強くなることはありませんでした。": { kana: "かふくぶがおもいかんじで、ずきずきはしません。きゅうにつよくなることはありませんでした。", romaji: "kafuku bu ga omoi kanji de、 zukizuki wa shi mase n。 kyuu ni tsuyoku naru koto wa ari mase n deshi ta。" },
  "予防接種は予定どおり受けています。発達も順調です。": { kana: "よぼうせっしゅはよていどおりうけています。はったつもじゅんちょうです。", romaji: "yoboo sesshu wa yotee doori uke te i masu。 hattatsu mo junchoo desu。" },
  "予防接種は受けていますか": { kana: "よぼうせっしゅはうけていますか", romaji: "yoboo sesshu wa uke te i masu ka" },
  "人の腸の中には、数百種類以上の細菌が住んでいる。かつては消化を助けるだけの存在と考えられていたが、近年の研究により、これらの細菌が免疫の働きにも深く関わっていることが明らかになってきた。": { kana: "ひとのちょうのなかには、すうひゃくしゅるいいじょうのさいきんがすんでいる。かつてはしょうかをたすけるだけのそんざいとかんがえられていたが、きんねんのけんきゅうにより、これらのさいきんがめんえきのはたらきにもふかくかかわっていることがあきらかになってきた。", romaji: "hito no choo no naka ni wa、 suuhyaku shurui ijoo no saikin ga sun de iru。 katsute wa shooka o tasukeru dake no sonzai to kangae rare te i ta ga、 kinnen no kenkyuu ni yori、 kore ra no saikin ga men'eki no hataraki ni mo fukaku kakawatsu te iru koto ga akiraka ni natsu te ki ta。" },
  "今までに大きな病気をされたことはありますか": { kana: "いままでにおおきなびょうきをされたことはありますか", romaji: "ima made ni ookina byooki o sa re ta koto wa ari masu ka" },
  "今何週目ですか": { kana: "いまなんしゅうめですか", romaji: "ima nan shuu me desu ka" },
  "今年度の住民検診を、下記の日程で実施します。対象は、市に住民登録のある40歳以上の方です。ただし、現在治療中の病気がある方、または妊娠中の方は、主治医にご相談のうえお申し込みください。": { kana: "こんねんどのじゅうみんけんしんを、かきのにっていでじっしします。たいしょうは、しにじゅうみんとうろくのある40さいいじょうのほうです。ただし、げんざいちりょうちゅうのびょうきがあるかた、またはにんしんちゅうのほうは、しゅじいにごそうだんのうえおもうしこみください。", romaji: "kon nendo no juumin kenshin o、 kaki no nittee de jisshi shi masu。 taishoo wa、 shi ni juumin tooroku no aru 40 sai ijoo no hoo desu。 tadashi、 genzai chiryoo chuu no byooki ga aru kata、 mata wa ninshin chuu no hoo wa、 shuji i ni go soodan no ue o mooshikomi kudasai。" },
  "今日の朝7時ごろからです。歩いていて急に痛くなりました。": { kana: "きょうのあさ7じごろからです。あるいていてきゅうにいたくなりました。", romaji: "kyoo no asa 7 ji goro kara desu。 arui te i te kyuu ni itaku nari mashi ta。" },
  "今日は1回だけです。": { kana: "きょうは1かいだけです。", romaji: "kyoo wa 1 kai dake desu。" },
  "今朝6時ごろ、起きたときからです。": { kana: "けさ6じごろ、おきたときからです。", romaji: "kesa 6 ji goro、 oki ta toki kara desu。" },
  "今朝から心臓がドキドキして、ふらつきます。": { kana: "けさからしんぞうがどきどきして、ふらつきます。", romaji: "kesa kara shinzoo ga dokidoki shi te、 furatsuki masu。" },
  "今朝は38.9度でした。解熱剤を飲むと少し下がります。": { kana: "けさは38.9どでした。げねつざいをのむとすこしさがります。", romaji: "kesa wa 38. 9 do deshi ta。 genetsu zai o nomu to sukoshi sagari masu。" },
  "他の病気はありますか": { kana: "ほかのびょうきはありますか", romaji: "hoka no byooki wa ari masu ka" },
  "以前にも同じことがありましたか": { kana: "いぜんにもおなじことがありましたか", romaji: "izen ni mo onaji koto ga ari mashi ta ka" },
  "以前に流産や子宮外妊娠はありましたか": { kana: "いぜんにりゅうざんやしきゅうがいにんしんはありましたか", romaji: "izen ni ryuuzan ya shikyuu gai ninshin wa ari mashi ta ka" },
  "会議室の都合により、同じ日の16時からに変更させていただきたく、お願い申し上げます。会議の内容と所要時間に変更はありません。1時間程度を予定しております。": { kana: "かいぎしつのつごうにより、おなじひの16じからにへんこうさせていただきたく、おねがいもうしあげます。かいぎのないようとしょようじかんにへんこうはありません。1じかんていどをよていしております。", romaji: "kaigi shitsu no tsugoo ni yori、 onaji hi no 16 ji kara ni henkoo sa se te itadaki taku、 o negai mooshiage masu。 kaigi no naiyoo to shoyoo jikan ni henkoo wa ari mase n。 1 jikan teedo o yotee shi te ori masu。" },
  "低血糖のような症状はありますか": { kana: "ていけっとうのようなしょうじょうはありますか", romaji: "tee kettoo no yoo na shoojoo wa ari masu ka" },
  "体重はどのくらい減りましたか": { kana: "たいじゅうはどのくらいへりましたか", romaji: "taijuu wa dono kurai heri mashi ta ka" },
  "体重は変わりましたか": { kana: "たいじゅうはかわりましたか", romaji: "taijuu wa kawari mashi ta ka" },
  "何か薬を飲みましたか": { kana: "なんかくすりをのみましたか", romaji: "nan ka kusuri o nomi mashi ta ka" },
  "何を食べたあとに症状が出ましたか": { kana: "なんをたべたあとにしょうじょうがでましたか", romaji: "nan o tabe ta ato ni shoojoo ga de mashi ta ka" },
  "何を食べましたか": { kana: "なんをたべましたか", romaji: "nan o tabe mashi ta ka" },
  "何回ありましたか": { kana: "なんかいありましたか", romaji: "nan kai ari mashi ta ka" },
  "何度ありましたか": { kana: "なんどありましたか", romaji: "nan do ari mashi ta ka" },
  "何時までは普通でしたか": { kana: "なんじまではふつうでしたか", romaji: "nan ji made wa futsuu deshi ta ka" },
  "先週、クリニックで心拍を確認しました。": { kana: "せんしゅう、くりにっくでしんぱくをかくにんしました。", romaji: "senshuu、 kurinikku de shinpaku o kakunin shi mashi ta。" },
  "全身がガタガタ震えていました。": { kana: "ぜんしんががたがたふるえていました。", romaji: "zenshin ga gatagata furue te i mashi ta。" },
  "全身が震えましたか、片側だけでしたか": { kana: "ぜんしんがふるえましたか、かたがわだけでしたか", romaji: "zenshin ga furue mashi ta ka、 katagawa dake deshi ta ka" },
  "全身のかゆみと息苦しさ": { kana: "ぜんしんのかゆみといきぐるしさ", romaji: "zenshin no kayumi to ikigurushi sa" },
  "冷や汗が出て、少し吐き気もします。息も苦しいです。": { kana: "ひやあせがでて、すこしはきけもします。いきもくるしいです。", romaji: "hiyaase ga de te、 sukoshi hakike mo shi masu。 iki mo kurushii desu。" },
  "冷や汗はありますか": { kana: "ひやあせはありますか", romaji: "hiyaase wa ari masu ka" },
  "冷や汗や手の震えはありますか": { kana: "ひやあせやてのふるえはありますか", romaji: "hiyaase ya te no furue wa ari masu ka" },
  "出血したことはありません。手術も受けたことはありません。": { kana: "しゅっけつしたことはありません。しゅじゅつもうけたことはありません。", romaji: "shukketsu shi ta koto wa ari mase n。 shujutsu mo uke ta koto wa ari mase n。" },
  "出血の量はどのくらいですか": { kana: "しゅっけつのりょうはどのくらいですか", romaji: "shukketsu no ryoo wa dono kurai desu ka" },
  "初めてです。": { kana: "はじめてです。", romaji: "hajimete desu。" },
  "制度を整えるだけで、この問題が自動的に解決するとは限らない。誰が、どの場面で、どちらを選ぶのかを、職場ごとに話し合って決めていく必要がある。": { kana: "せいどをととのえるだけで、このもんだいがじどうてきにかいけつするとはかぎらない。だれが、どのばめんで、どちらをえらぶのかを、しょくばごとにはなしあってきめていくひつようがある。", romaji: "seedo o totonoeru dake de、 kono mondai ga jidoo teki ni kaiketsu suru to wa kagira nai。 dare ga、 dono bamen de、 dochira o erabu no ka o、 shokuba goto ni hanashiatsu te kime te iku hitsuyoo ga aru。" },
  "動くと痛くなりますか": { kana: "うごくといたくなりますか", romaji: "ugoku to itaku nari masu ka" },
  "動悸とふらつき": { kana: "どうきとふらつき", romaji: "dooki to furatsuki" },
  "医療の現場で「説明した」という言葉は、しばしば二つの異なる行為を指している。一つは情報を伝えること、もう一つは相手が理解した状態を作ることである。この二つは似て見えて、求められる技術がまったく違う。": { kana: "いりょうのげんばで「せつめいした」ということばは、しばしばふたつのことなるこういをさしている。ひとつはじょうほうをつたえること、もうひとつはあいてがりかいしたじょうたいをつくることである。このふたつはにてみえて、もとめられるぎじゅつがまったくちがう。", romaji: "iryoo no genba de「 setsumee shi ta」 to yuu kotoba wa、 shibashiba futa tsu no kotonaru kooi o sashi te iru。 hito tsu wa joohoo o tsutaeru koto、 moo hito tsu wa aite ga rikai shi ta jootai o tsukuru koto de aru。 kono futa tsu wa ni te mie te、 motome rareru gijutsu ga mattaku chigau。" },
  "右手が動かない": { kana: "みぎてがうごかない", romaji: "migite ga ugoka nai" },
  "右手は動きませんが、足は何とか動きます。話しにくいです。": { kana: "みぎてはうごきませんが、あしはなんとかうごきます。はなしにくいです。", romaji: "migite wa ugoki mase n ga、 ashi wa nan to ka ugoki masu。 hanashi nikui desu。" },
  "吐きましたか": { kana: "はきましたか", romaji: "haki mashi ta ka" },
  "吐き気はありますか": { kana: "はきけはありますか", romaji: "hakike wa ari masu ka" },
  "問題は、プラセボ効果を意図的に使うことが許されるかどうかである。効果があるように見せるために、実際には有効性のない治療を勧めることは、患者の利益にならない。したがって、議論の中心は、効果の有無ではなく、それがどういう仕組みで生じ、どの範囲で患者の役に立つのかという点にあるべきだ。": { kana: "もんだいは、ぷらせぼこうかをいとてきにつかうことがゆるされるかどうかである。こうかがあるようにみせるために、じっさいにはゆうこうせいのないちりょうをすすめることは、かんじゃのりえきにならない。したがって、ぎろんのちゅうしんは、こうかのうむではなく、それがどういうしくみでしょうじ、どのはんいでかんじゃのやくにたつのかというてんにあるべきだ。", romaji: "mondai wa、 purasebo kooka o ito teki ni tsukau koto ga yurusa reru ka doo ka de aru。 kooka ga aru yoo ni miseru tame ni、 jissai ni wa yuukoo see no nai chiryoo o susumeru koto wa、 kanja no rieki ni nara nai。 shitagatsu te、 giron no chuushin wa、 kooka no umu de wa naku、 sore ga doo yuu shikumi de shooji、 dono han'i de kanja no yaku ni tatsu no ka to yuu ten ni aru beki da。" },
  "喘息の吸入薬を使っています。アドレナリンは持っていません。": { kana: "ぜんそくのきゅうにゅうやくをつかっています。あどれなりんはもっていません。", romaji: "zensoku no kyuunyuu yaku o tsukatsu te i masu。 adorenarin wa motsu te i mase n。" },
  "在宅勤務が広がって数年が経った。通勤時間がなくなり、育児や介護と両立しやすくなったという声は多い。実際、通勤に使っていた時間を自分のために使えるようになった人は少なくないだろう。": { kana: "ざいたくきんむがひろがってすうねんがたった。つうきんじかんがなくなり、いくじやかいごとりょうりつしやすくなったというこえはおおい。じっさい、つうきんにつかっていたじかんをじぶんのためにつかえるようになったひとはすくなくないだろう。", romaji: "zaitaku kinmu ga hirogatsu te suu nen ga tatsu ta。 tsuukin jikan ga nakunari、 ikuji ya kaigo to ryooritsu shi yasuku natsu ta to yuu koe wa ooi。 jissai、 tsuukin ni tsukatsu te i ta jikan o jibun no tame ni tsukaeru yoo ni natsu ta hito wa sukunaku nai daroo。" },
  "基礎疾患はありますか": { kana: "きそしっかんはありますか", romaji: "kiso shikkan wa ari masu ka" },
  "塊は出ていません。": { kana: "かたまりはでていません。", romaji: "katamari wa de te i mase n。" },
  "声は出しにくくないですか": { kana: "こえはだしにくくないですか", romaji: "koe wa dashi nikuku nai desu ka" },
  "失神しましたか": { kana: "しっしんしましたか", romaji: "shisshin shi mashi ta ka" },
  "妊娠の可能性はありますか": { kana: "にんしんのかのうせいはありますか", romaji: "ninshin no kanoo see wa ari masu ka" },
  "妊娠の確認は医療機関で受けましたか": { kana: "にんしんのかくにんはいりょうきかんでうけましたか", romaji: "ninshin no kakunin wa iryoo kikan de uke mashi ta ka" },
  "家で2分くらい体が震えて、目が上を向いていました。": { kana: "いえで2ふんくらいからだがふるえて、めがうえをむいていました。", romaji: "ie de 2 fun kurai karada ga furue te、 me ga ue o mui te i mashi ta。" },
  "家で薬を飲みましたか": { kana: "いえでくすりをのみましたか", romaji: "ie de kusuri o nomi mashi ta ka" },
  "家にあった痛み止めを1錠飲みました。": { kana: "いえにあったいたみどめを1じょうのみました。", romaji: "ie ni atsu ta itamidome o 1 joo nomi mashi ta。" },
  "家族です。延命は望んでいませんが、苦しくないようにしてほしいです。": { kana: "かぞくです。えんめいはのぞんでいませんが、くるしくないようにしてほしいです。", romaji: "kazoku desu。 enmee wa nozon de i mase n ga、 kurushiku nai yoo ni shi te hoshii desu。" },
  "少しぼやけることがあります。": { kana: "すこしぼやけることがあります。", romaji: "sukoshi boyakeru koto ga ari masu。" },
  "少し息苦しくて、横になると楽です。": { kana: "すこしいきぐるしくて、よこになるとらくです。", romaji: "sukoshi ikigurushiku te、 yoko ni naru to raku desu。" },
  "少量の出血と下腹部痛": { kana: "しょうりょうのしゅっけつとかふくぶつう", romaji: "shooryoo no shukketsu to kafuku bu tsuu" },
  "尿が濃くて、においが強いと言われました。量も少ないです。": { kana: "にょうがこくて、においがつよいといわれました。りょうもすくないです。", romaji: "nyoo ga koku te、 nioi ga tsuyoi to iwa re mashi ta。 ryoo mo sukunai desu。" },
  "尿のにおいは変わっていませんか": { kana: "にょうのにおいはかわっていませんか", romaji: "nyoo no nioi wa kawatsu te i mase n ka" },
  "尿の色は変わりましたか": { kana: "にょうのいろはかわりましたか", romaji: "nyoo no iro wa kawari mashi ta ka" },
  "尿の量は減っていませんか": { kana: "にょうのりょうはへっていませんか", romaji: "nyoo no ryoo wa hetsu te i mase n ka" },
  "左の肩と腕のほうに広がります。": { kana: "ひだりのかたとうでのほうにひろがります。", romaji: "hidari no kata to ude no hoo ni hirogari masu。" },
  "座っていると少し楽ですが、立つとくらくらします。": { kana: "すわっているとすこしらくですが、たつとくらくらします。", romaji: "suwatsu te iru to sukoshi raku desu ga、 tatsu to kurakura shi masu。" },
  "延命の希望について伺ってもよろしいですか": { kana: "えんめいのきぼうについてうかがってもよろしいですか", romaji: "enmee no kiboo ni tsui te ukagatsu te mo yoroshii desu ka" },
  "当院では、4月1日より土曜日の診療時間を変更いたします。これまで土曜日は午前9時から午後1時まででしたが、4月からは午前8時30分から午後12時30分までとなります。平日の診療時間に変更はありません。": { kana: "とういんでは、4がつ1かよりどようひのしんりょうじかんをへんこういたします。これまでどようひはごぜん9じからごご1じまででしたが、4がつからはごぜん8じ30ふんからごご12じ30ふんまでとなります。へいじつのしんりょうじかんにへんこうはありません。", romaji: "tooin de wa、 4 gatsu 1 ka yori doyoo hi no shinryoo jikan o henkoo itashi masu。 kore made doyoo hi wa gozen 9 ji kara gogo 1 ji made deshi ta ga、 4 gatsu kara wa gozen 8 ji 30 fun kara gogo 12 ji 30 fun made to nari masu。 heejitsu no shinryoo jikan ni henkoo wa ari mase n。" },
  "心房細動と言われています。高血圧もあります。": { kana: "しんぼうさいどうといわれています。こうけつあつもあります。", romaji: "shinboo saidoo to iwa re te i masu。 koo ketsuatsu mo ari masu。" },
  "心臓の病気はありますか": { kana: "しんぞうのびょうきはありますか", romaji: "shinzoo no byooki wa ari masu ka" },
  "息は苦しいですか": { kana: "いきはくるしいですか", romaji: "iki wa kurushii desu ka" },
  "息は苦しくないですか": { kana: "いきはくるしくないですか", romaji: "iki wa kurushiku nai desu ka" },
  "息苦しさはありますか": { kana: "いきぐるしさはありますか", romaji: "ikigurushi sa wa ari masu ka" },
  "情報を伝えるだけなら、正しい内容を整理して話せばよい。しかし、理解を作るには、相手がすでに持っている知識や、これまでに経験した病気の記憶を踏まえなければならない。同じ一文でも、これまでに何を聞いてきたかによって、届く意味は変わる。": { kana: "じょうほうをつたえるだけなら、ただしいないようをせいりしてはなせばよい。しかし、りかいをつくるには、あいてがすでにもっているちしきや、これまでにけいけんしたびょうきのきおくをふまえなければならない。おなじいちぶんでも、これまでになんをきいてきたかによって、とどくいみはかわる。", romaji: "joohoo o tsutaeru dake nara、 tadashii naiyoo o seeri shi te hanase ba yoi。 shikashi、 rikai o tsukuru ni wa、 aite ga sudeni motsu te iru chishiki ya、 kore made ni keeken shi ta byooki no kioku o fumae nakere ba nara nai。 onaji ichi bun de mo、 kore made ni nan o kii te ki ta ka ni yotsu te、 todoku imi wa kawaru。" },
  "意識はあります。ぼんやりはしていません。": { kana: "いしきはあります。ぼんやりはしていません。", romaji: "ishiki wa ari masu。 bonyari wa shi te i mase n。" },
  "意識ははっきりしていますか": { kana: "いしきははっきりしていますか", romaji: "ishiki wa hakkiri shi te i masu ka" },
  "手術を受けましたか": { kana: "しゅじゅつをうけましたか", romaji: "shujutsu o uke mashi ta ka" },
  "手足のしびれはありますか": { kana: "てあしのしびれはありますか", romaji: "teashi no shibire wa ari masu ka" },
  "抗凝固薬は飲んでいますか": { kana: "こうぎょうこやくはのんでいますか", romaji: "koo gyooko yaku wa non de i masu ka" },
  "抗菌薬を最近使いましたか": { kana: "こうきんやくをさいきんつかいましたか", romaji: "kookin yaku o saikin tsukai mashi ta ka" },
  "排尿時の痛みはありますか": { kana: "はいにょうじのいたみはありますか", romaji: "hainyoo ji no itami wa ari masu ka" },
  "救急車の前に何か投与されましたか": { kana: "きゅうきゅうしゃのまえになんかとうよされましたか", romaji: "kyuukyuu sha no mae ni nan ka tooyo sa re mashi ta ka" },
  "救急隊の方が何かしました。よく分かりません。": { kana: "きゅうきゅうたいのほうがなんかしました。よくわかりません。", romaji: "kyuukyuu tai no hoo ga nan ka shi mashi ta。 yoku wakari mase n。" },
  "昔、ペニシリンで発疹が出ました。": { kana: "むかし、ぺにしりんではっしんがでました。", romaji: "mukashi、 penishirin de hasshin ga de mashi ta。" },
  "昨夜11時ごろからです。": { kana: "さくや11じごろからです。", romaji: "sakuya 11 ji goro kara desu。" },
  "昨夜からです。施設で37.9度出ています。": { kana: "さくやからです。しせつで37.9どでています。", romaji: "sakuya kara desu。 shisetsu de 37. 9 do de te i masu。" },
  "昨夜から熱が出て、声をかけても返事が少なくなりました。": { kana: "さくやからねつがでて、こえをかけてもへんじがすくなくなりました。", romaji: "sakuya kara netsu ga de te、 koe o kake te mo henji ga sukunaku nari mashi ta。" },
  "昨日から少し出血があって、おなかも痛いです。": { kana: "きのうからすこししゅっけつがあって、おなかもいたいです。", romaji: "kinoo kara sukoshi shukketsu ga atsu te、 onaka mo itai desu。" },
  "昨日から横になると息苦しくて、枕を高くしています。": { kana: "きのうからよこになるといきぐるしくて、まくらをたかくしています。", romaji: "kinoo kara yoko ni naru to ikigurushiku te、 makura o takaku shi te i masu。" },
  "昨日の夜から38度台です。": { kana: "きのうのよるから38どだいです。", romaji: "kinoo no yoru kara 38 do dai desu。" },
  "昨日の夜からおなかが痛いです。今は右下が特に痛いです。": { kana: "きのうのよるからおなかがいたいです。いまはみぎしたがとくにいたいです。", romaji: "kinoo no yoru kara onaka ga itai desu。 ima wa migishita ga tokuni itai desu。" },
  "昨日は半分も食べていません。水分も少ないです。": { kana: "きのうははんぶんもたべていません。すいぶんもすくないです。", romaji: "kinoo wa hanbun mo tabe te i mase n。 suibun mo sukunai desu。" },
  "昨日は普通に働いていました。": { kana: "きのうはふつうにはたらいていました。", romaji: "kinoo wa futsuu ni hatarai te i mashi ta。" },
  "普段どおり動けますか": { kana: "ふだんどおりうごけますか", romaji: "fudan doori ugoke masu ka" },
  "普段は2階に上がれますが、今日は階段の前で休みました。": { kana: "ふだんは2かいにあがれますが、きょうはかいだんのまえでやすみました。", romaji: "fudan wa 2 kai ni agare masu ga、 kyoo wa kaidan no mae de yasumi mashi ta。" },
  "普段はどんな様子ですか": { kana: "ふだんはどんなようすですか", romaji: "fudan wa donna yoosu desu ka" },
  "普段は簡単な会話はできます。今日は名前を呼んでも反応が遅いです。": { kana: "ふだんはかんたんなかいわはできます。きょうはなまえをよんでもはんのうがおそいです。", romaji: "fudan wa kantan na kaiwa wa deki masu。 kyoo wa namae o yon de mo hannoo ga osoi desu。" },
  "最初はおへその周りが痛くて、今朝から右下に移りました。": { kana: "さいしょはおへそのまわりがいたくて、けさからみぎしたにうつりました。", romaji: "saisho wa o heso no mawari ga itaku te、 kesa kara migishita ni utsuri mashi ta。" },
  "最後に正常だったのは何時ですか": { kana: "さいごにせいじょうだったのはいつですか", romaji: "saigo ni seejoo datsu ta no wa itsu desu ka" },
  "最後の生理はいつですか": { kana: "さいごのせいりはいつですか", romaji: "saigo no seeri wa itsu desu ka" },
  "最終月経から9週目だと思います。": { kana: "さいしゅうげっけいから9しゅうめだとおもいます。", romaji: "saishuu gekkee kara 9 shuu me da to omoi masu。" },
  "最終月経はいつですか": { kana: "さいしゅうげっけいはいつですか", romaji: "saishuu gekkee wa itsu desu ka" },
  "最近出血しましたか": { kana: "さいきんしゅっけつしましたか", romaji: "saikin shukketsu shi mashi ta ka" },
  "最高で何度でしたか": { kana: "さいこうでなんどでしたか", romaji: "saikoo de nan do deshi ta ka" },
  "朝6時半までは普通に朝食を食べていました。": { kana: "あさ6じはんまではふつうにちょうしょくをたべていました。", romaji: "asa 6 ji han made wa futsuu ni chooshoku o tabe te i mashi ta。" },
  "朝から胸が苦しくて、冷や汗が出ます。": { kana: "あさからむねがくるしくて、ひやあせがでます。", romaji: "asa kara mune ga kurushiku te、 hiyaase ga de masu。" },
  "朝食は食べられましたが、今は水を飲むのは不安です。": { kana: "ちょうしょくはたべられましたが、いまはみずをのむのはふあんです。", romaji: "chooshoku wa tabe rare mashi ta ga、 ima wa mizu o nomu no wa fuan desu。" },
  "検診の種類は、胃がん・大腸がん・肺がん・乳がん・子宮頸がんの5つです。乳がん検診は40歳以上の女性、子宮頸がん検診は20歳以上の女性が対象です。前回の検診から1年未満の方は、受診できません。": { kana: "けんしんのしゅるいは、いがん・だいちょうがん・はいがん・にゅうがん・しきゅうけいがんの5つです。にゅうがんけんしんは40さいいじょうのじょせい、しきゅうけいがんけんしんは20さいいじょうのじょせいがたいしょうです。ぜんかいのけんしんから1ねんみまんのほうは、じゅしんできません。", romaji: "kenshin no shurui wa、 igan・ daichoo gan・ haigan・ nyuugan・ shikyuu keegan no 5 tsu desu。 nyuugan kenshin wa 40 sai ijoo no josee、 shikyuu keegan kenshin wa 20 sai ijoo no josee ga taishoo desu。 zenkai no kenshin kara 1 nen miman no hoo wa、 jushin deki mase n。" },
  "検診の結果は、受診から約1か月後に郵送します。結果の説明が必要な方には、地域の医療機関での相談をご案内します。異常が見つかった場合でも、必ずしも重い病気というわけではありませんが、早めの確認をおすすめします。": { kana: "けんしんのけっかは、じゅしんからやく1かげつごにゆうそうします。けっかのせつめいがひつようなかたには、ちいきのいりょうきかんでのそうだんをごあんないします。いじょうがみつかったばあいでも、かならずしもおもいびょうきというわけではありませんが、はやめのかくにんをおすすめします。", romaji: "kenshin no kekka wa、 jushin kara yaku 1 kagetsu go ni yuusoo shi masu。 kekka no setsumee ga hitsuyoo na kata ni wa、 chiiki no iryoo kikan de no soodan o go annai shi masu。 ijoo ga mitsukatsu ta baai de mo、 kanarazu shimo omoi byooki to yuu wake de wa ari mase n ga、 hayame no kakunin o o susume shi masu。" },
  "歩くと痛くて、体を丸めています。咳をすると響きます。": { kana: "あるくといたくて、からだをまるめています。せきをするとひびきます。", romaji: "aruku to itaku te、 karada o marume te i masu。 seki o suru to hibiki masu。" },
  "歩くと痛みますか": { kana: "あるくといたみますか", romaji: "aruku to itami masu ka" },
  "母乳は飲んでいます。おしっこは朝から2回です。": { kana: "ぼにゅうはのんでいます。おしっこはあさから2かいです。", romaji: "bonyuu wa non de i masu。 oshikko wa asa kara 2 kai desu。" },
  "毎日、朝の体重と血圧を記録してください。2日間で体重が2キロ以上増えた場合、足のむくみが強くなった場合、安静にしていても息苦しい場合は、次の予約を待たずにご連絡ください。": { kana: "まいにち、あさのたいじゅうとけつあつをきろくしてください。2かかんでたいじゅうが2きろいじょうふえたばあい、あしのむくみがつよくなったばあい、あんせいにしていてもいきぐるしいばあいは、つぎのよやくをまたずにごれんらくください。", romaji: "mainichi、 asa no taijuu to ketsuatsu o kiroku shi te kudasai。 2 kakan de taijuu ga 2 kiro ijoo fue ta baai、 ashi no mukumi ga tsuyoku natsu ta baai、 ansee ni shi te i te mo ikigurushii baai wa、 tsugi no yoyaku o mata zu ni go renraku kudasai。" },
  "気を失いそうですか": { kana: "きをうしないそうですか", romaji: "ki o ushinai soo desu ka" },
  "気を失いましたか": { kana: "きをうしないましたか", romaji: "ki o ushinai mashi ta ka" },
  "気を失ったことはありますか": { kana: "きをうしなったことはありますか", romaji: "ki o ushinatsu ta koto wa ari masu ka" },
  "気を失ってはいませんが、立つとふらつきます。": { kana: "きをうしなってはいませんが、たつとふらつきます。", romaji: "ki o ushinatsu te wa i mase n ga、 tatsu to furatsuki masu。" },
  "水は飲めましたか": { kana: "みずはのめましたか", romaji: "mizu wa nome mashi ta ka" },
  "水を1日3リットルくらい飲みます。夜も2回トイレに起きます。": { kana: "みずを1か3りっとるくらいのみます。よるも2かいといれにおきます。", romaji: "mizu o 1 ka 3 rittoru kurai nomi masu。 yoru mo 2 kai toire ni oki masu。" },
  "水分は取れていますか": { kana: "すいぶんはとれていますか", romaji: "suibun wa tore te i masu ka" },
  "熱と咳が続く": { kana: "ねつとせきがつづく", romaji: "netsu to seki ga tsuzuku" },
  "熱はありますか": { kana: "ねつはありますか", romaji: "netsu wa ari masu ka" },
  "熱はいつからですか": { kana: "ねつはいつからですか", romaji: "netsu wa itsu kara desu ka" },
  "熱はどのくらいですか": { kana: "ねつはどのくらいですか", romaji: "netsu wa dono kurai desu ka" },
  "父が糖尿病です。": { kana: "ちちがとうにょうびょうです。", romaji: "chichi ga toonyoo byoo desu。" },
  "特に飲んでいません。お薬手帳は持っていません。": { kana: "とくにのんでいません。おくすりてちょうはもっていません。", romaji: "tokuni non de i mase n。 o kusuri techoo wa motsu te i mase n。" },
  "現時点で確かなのは、食事の内容が腸内細菌の構成に影響するということ、そしてその影響が数週間で現れるということだ。何が最適かは、まだ研究の途中である。": { kana: "げんじてんでたしかなのは、しょくじのないようがちょうないさいきんのこうせいにえいきょうするということ、そしてそのえいきょうがすうしゅうかんであらわれるということだ。なんがさいてきかは、まだけんきゅうのとちゅうである。", romaji: "gen jiten de tashika na no wa、 shokuji no naiyoo ga choonai saikin no koosee ni eekyoo suru to yuu koto、 soshite sono eekyoo ga suu shuukan de arawareru to yuu koto da。 nan ga saiteki ka wa、 mada kenkyuu no tochuu de aru。" },
  "田中部長\n\nお疲れさまです。企画課の佐藤です。来週火曜日14時から予定しておりました定例会議について、ご連絡いたします。": { kana: "たなかぶちょうおつかれさまです。きかくかのさとうです。らいしゅうかようひ14じからよていしておりましたていれいかいぎについて、ごれんらくいたします。", romaji: "tanaka bu choo o tsukare sama desu。 kikaku ka no satoo desu。 raishuu kayoo hi 14 ji kara yotee shi te ori mashi ta teeree kaigi ni tsui te、 go renraku itashi masu。" },
  "甲状腺の病気はありますか": { kana: "こうじょうせんのびょうきはありますか", romaji: "koojoo sen no byooki wa ari masu ka" },
  "甲状腺は言われたことがありません。お酒は飲みません。": { kana: "こうじょうせんはいわれたことがありません。おさけはのみません。", romaji: "koojoo sen wa iwa re ta koto ga ari mase n。 o sake wa nomi mase n。" },
  "申し込みは、電話または市のホームページから、実施日の2週間前までにお願いします。定員に達した場合は、期日前でも受付を終了することがあります。": { kana: "もうしこみは、でんわまたはしのほーむぺーじから、じっしひの2しゅうかんまえまでにおねがいします。ていいんにたっしたばあいは、きじつまえでもうけつけをしゅうりょうすることがあります。", romaji: "mooshikomi wa、 denwa mata wa shi no hoomu peeji kara、 jisshi hi no 2 shuukan mae made ni o negai shi masu。 teein ni tasshi ta baai wa、 kijitsu mae de mo uketsuke o shuuryoo suru koto ga ari masu。" },
  "男性なので関係ないと思います。": { kana: "だんせいなのでかんけいないとおもいます。", romaji: "dansee na no de kankee nai to omoi masu。" },
  "症状はいつからですか": { kana: "しょうじょうはいつからですか", romaji: "shoojoo wa itsu kara desu ka" },
  "症状はいつ始まりましたか": { kana: "しょうじょうはいつはじまりましたか", romaji: "shoojoo wa itsu hajimari mashi ta ka" },
  "痛がるところはありませんか": { kana: "いたがるところはありませんか", romaji: "ita garu tokoro wa ari mase n ka" },
  "痛みはいつからですか": { kana: "いたみはいつからですか", romaji: "itami wa itsu kara desu ka" },
  "痛みはどれくらいですか": { kana: "いたみはどれくらいですか", romaji: "itami wa dore kurai desu ka" },
  "痛みは他の場所に広がりますか": { kana: "いたみはたのばしょにひろがりますか", romaji: "itami wa ta no basho ni hirogari masu ka" },
  "痛みは急に強くなりましたか": { kana: "いたみはきゅうにつよくなりましたか", romaji: "itami wa kyuu ni tsuyoku nari mashi ta ka" },
  "痛みは最初どこでしたか": { kana: "いたみはさいしょどこでしたか", romaji: "itami wa saisho doko deshi ta ka" },
  "痛みを0から10で表すとどのくらいですか": { kana: "いたみを0から10であらわすとどのくらいですか", romaji: "itami o 0 kara 10 de arawasu to dono kurai desu ka" },
  "痛み止めを飲みましたか": { kana: "いたみどめをのみましたか", romaji: "itamidome o nomi mashi ta ka" },
  "痛む場所は変わりましたか": { kana: "いたむばしょはかわりましたか", romaji: "itamu basho wa kawari mashi ta ka" },
  "痰の色はどのようですか": { kana: "たんのいろはどのようですか", romaji: "tan no iro wa dono yoo desu ka" },
  "痰は出ますか": { kana: "たんはでますか", romaji: "tan wa de masu ka" },
  "発熱と意識状態の悪化": { kana: "はつねつといしきじょうたいのあっか", romaji: "hatsunetsu to ishiki jootai no akka" },
  "発達は順調ですか": { kana: "はったつはじゅんちょうですか", romaji: "hattatsu wa junchoo desu ka" },
  "目のかすみはありますか": { kana: "めのかすみはありますか", romaji: "me no kasumi wa ari masu ka" },
  "眠りの質を高める方法は、それほど特別ではない。朝は同じ時刻に起き、日中の光を浴び、カフェインを午後は控え、就寝前の刺激を減らす。これらは地味だが、効果が確認されている。": { kana: "ねむりのしつをたかめるほうほうは、それほどとくべつではない。あさはおなじじこくにおき、にっちゅうのひかりをあび、かふぇいんをごごはひかえ、しゅうしんまえのしげきをへらす。これらはじみだが、こうかがかくにんされている。", romaji: "nemuri no shitsu o takameru hoohoo wa、 sore hodo tokubetsu de wa nai。 asa wa onaji jikoku ni oki、 nitchuu no hikari o abi、 kafein o gogo wa hikae、 shuushin mae no shigeki o herasu。 kore ra wa jimi da ga、 kooka ga kakunin sa re te iru。" },
  "睡眠は、単に体を休める時間ではない。眠っている間、体の中では免疫に関わる細胞の活動が高まり、日中に受けた傷の修復が進む。つまり、睡眠は回復のための作業時間なのである。": { kana: "すいみんは、たんにからだをやすめるじかんではない。ねむっているあいだ、からだのなかではめんえきにかかわるさいぼうのかつどうがたかまり、にっちゅうにうけたきずのしゅうふくがすすむ。つまり、すいみんはかいふくのためのさぎょうじかんなのである。", romaji: "suimin wa、 tanni karada o yasumeru jikan de wa nai。 nemutsu te iru aida、 karada no naka de wa men'eki ni kakawaru saiboo no katsudoo ga takamari、 nitchuu ni uke ta kizu no shuufuku ga susumu。 tsumari、 suimin wa kaifuku no tame no sagyoo jikan na no de aru。" },
  "睡眠時間が短い状態が続くと、感染症にかかりやすくなるという報告がある。ただし、長時間眠れば必ず健康になるとは限らない。重要なのは時間だけでなく、眠りの深さと規則性である。": { kana: "すいみんじかんがみじかいじょうたいがつづくと、かんせんしょうにかかりやすくなるというほうこくがある。ただし、ちょうじかんねむればかならずけんこうになるとはかぎらない。じゅうようなのはじかんだけでなく、ねむりのふかさときそくせいである。", romaji: "suimin jikan ga mijikai jootai ga tsuzuku to、 kansen shoo ni kakari yasuku naru to yuu hookoku ga aru。 tadashi、 choo jikan nemure ba kanarazu kenkoo ni naru to wa kagira nai。 juuyoo na no wa jikan dake de naku、 nemuri no fuka sa to kisoku see de aru。" },
  "私も子供の頃に熱性けいれんがありました。": { kana: "わたくしもこどものころにねっせいけいれんがありました。", romaji: "watakushi mo kodomo no koro ni nessee keeren ga ari mashi ta。" },
  "立つとふらつきますか": { kana: "たつとふらつきますか", romaji: "tatsu to furatsuki masu ka" },
  "終わってから5分くらいで泣き始め、今はいつもどおりです。": { kana: "おわってから5ふんくらいでなきはじめ、いまはいつもどおりです。", romaji: "owatsu te kara 5 fun kurai de naki hajime、 ima wa itsu mo doori desu。" },
  "絨毛のようなものは出ましたか": { kana: "じゅうもうのようなものはでましたか", romaji: "juumoo no yoo na mono wa de mashi ta ka" },
  "肩の痛みはありますか": { kana: "かたのいたみはありますか", romaji: "kata no itami wa ari masu ka" },
  "肩や腕に広がりますか": { kana: "かたやうでにひろがりますか", romaji: "kata ya ude ni hirogari masu ka" },
  "胸が痛くないですか": { kana: "むねがいたくないですか", romaji: "mune ga itaku nai desu ka" },
  "胸が締め付けられるように痛い": { kana: "むねがしめつけられるようにいたい", romaji: "mune ga shimetsuke rareru yoo ni itai" },
  "胸の痛みはありますか": { kana: "むねのいたみはありますか", romaji: "mune no itami wa ari masu ka" },
  "胸の痛みはありません。": { kana: "むねのいたみはありません。", romaji: "mune no itami wa ari mase n。" },
  "胸の痛みはいつからですか": { kana: "むねのいたみはいつからですか", romaji: "mune no itami wa itsu kara desu ka" },
  "脳出血の既往はありますか": { kana: "のうしゅっけつのきおうはありますか", romaji: "noo shukketsu no kioo wa ari masu ka" },
  "薬のアレルギーはありますか": { kana: "くすりのあれるぎーはありますか", romaji: "kusuri no arerugii wa ari masu ka" },
  "薬のアレルギーは聞いたことがありません。": { kana: "くすりのあれるぎーはきいたことがありません。", romaji: "kusuri no arerugii wa kii ta koto ga ari mase n。" },
  "薬は飲んでいません。初めての妊娠です。": { kana: "くすりはのんでいません。はじめてのにんしんです。", romaji: "kusuri wa non de i mase n。 hajimete no ninshin desu。" },
  "血の塊は出ましたか": { kana: "ちのかたまりはでましたか", romaji: "chi no katamari wa de mashi ta ka" },
  "血の量は増えていますか": { kana: "ちのりょうはふえていますか", romaji: "chi no ryoo wa fue te i masu ka" },
  "血をさらさらにする薬は飲んでいますか": { kana: "ちをさらさらにするくすりはのんでいますか", romaji: "chi o sarasara ni suru kusuri wa non de i masu ka" },
  "血をさらさらにする薬は飲んでいません。": { kana: "ちをさらさらにするくすりはのんでいません。", romaji: "chi o sarasara ni suru kusuri wa non de i mase n。" },
  "血をさらさらにする薬を飲んでいますか": { kana: "ちをさらさらにするくすりをのんでいますか", romaji: "chi o sarasara ni suru kusuri o non de i masu ka" },
  "血圧が高いと言われたことがありますが、放っています。": { kana: "けつあつがたかいといわれたことがありますが、ほうっています。", romaji: "ketsuatsu ga takai to iwa re ta koto ga ari masu ga、 hootsu te i masu。" },
  "血圧が高いと言われていますが、薬は飲んでいません。タバコは1日20本です。": { kana: "けつあつがたかいといわれていますが、くすりはのんでいません。たばこは1か20ぽんです。", romaji: "ketsuatsu ga takai to iwa re te i masu ga、 kusuri wa non de i mase n。 tabako wa 1 ka 20 pon desu。" },
  "血圧の薬を2種類飲んでいます。お薬手帳を持ってきました。": { kana: "けつあつのくすりを2しゅるいのんでいます。おくすりてちょうをもってきました。", romaji: "ketsuatsu no kusuri o 2 shurui non de i masu。 o kusuri techoo o motsu te ki mashi ta。" },
  "血圧やコレステロールを言われたことはありますか": { kana: "けつあつやこれすてろーるをいわれたことはありますか", romaji: "ketsuatsu ya koresuterooru o iwa re ta koto wa ari masu ka" },
  "血液型はご存じですか": { kana: "けつえきがたはごぞんじですか", romaji: "ketsueki gata wa go zonji desu ka" },
  "視力は変わりましたか": { kana: "しりょくはかわりましたか", romaji: "shiryoku wa kawari mashi ta ka" },
  "話しにくさはありますか": { kana: "はなしにくさはありますか", romaji: "hanashi niku sa wa ari masu ka" },
  "説明が理解に至ったかどうかを確かめる方法は、それほど難しくない。患者に自分の言葉で言い直してもらうことである。うまく言い直せなければ、理解ではなく記憶が起きているだけかもしれない。": { kana: "せつめいがりかいにいたったかどうかをたしかめるほうほうは、それほどむずかしくない。かんじゃにじぶんのことばでいいなおしてもらうことである。うまくいいなおせなければ、りかいではなくきおくがおきているだけかもしれない。", romaji: "setsumee ga rikai ni itatsu ta ka doo ka o tashikameru hoohoo wa、 sore hodo muzukashiku nai。 kanja ni jibun no kotoba de iinaoshi te morau koto de aru。 umaku iinaose nakere ba、 rikai de wa naku kioku ga oki te iru dake ka mo shire nai。" },
  "超音波検査は受けましたか": { kana: "ちょうおんぱけんさはうけましたか", romaji: "choo onpa kensa wa uke mashi ta ka" },
  "足の感覚は変わりませんか": { kana: "あしのかんかくはかわりませんか", romaji: "ashi no kankaku wa kawari mase n ka" },
  "足の裏が少ししびれる感じがあります。": { kana: "あしのうらがすこししびれるかんじがあります。", romaji: "ashi no ura ga sukoshi shibireru kanji ga ari masu。" },
  "転んでから、血をさらさらにする薬はやめていました。": { kana: "ころんでから、ちをさらさらにするくすりはやめていました。", romaji: "koron de kara、 chi o sarasara ni suru kusuri wa yame te i mashi ta。" },
  "退院後は、処方された薬を指示どおりに飲み続けてください。調子が良くなっても、自己判断で量を変えたり中止したりしないでください。飲み忘れに気づいた場合は、次の分とまとめて飲まずに、気づいた時点で一回分だけ飲んでください。": { kana: "たいいんごは、しょほうされたくすりをしじどおりにのみつづけてください。ちょうしがよくなっても、じこはんだんでりょうをかえたりちゅうししたりしないでください。のみわすれにきづいたばあいは、つぎのぶんとまとめてのまずに、きづいたじてんでいちかいぶんだけのんでください。", romaji: "taiin go wa、 shohoo sa re ta kusuri o shiji doori ni nomi tsuzuke te kudasai。 chooshi ga yoku natsu te mo、 jiko handan de ryoo o kae tari chuushi shi tari shi nai de kudasai。 nomi wasure ni kizui ta baai wa、 tsugi no bun to matome te noma zu ni、 kizui ta jiten de ichi kai bun dake non de kudasai。" },
  "運動は、軽い散歩から始めてください。息が弾む程度で、誰かと話しながら歩ける強さが目安です。痛みや強い息苦しさが出た場合は中止し、次の外来でご相談ください。": { kana: "うんどうは、かるいさんぽからはじめてください。いきがはずむていどで、だれかとはなしながらあるけるつよさがめやすです。いたみやつよいいきぐるしさがでたばあいはちゅうしし、つぎのがいらいでごそうだんください。", romaji: "undoo wa、 karui sanpo kara hajime te kudasai。 iki ga hazumu teedo de、 dare ka to hanashi nagara arukeru tsuyo sa ga meyasu desu。 itami ya tsuyoi ikigurushi sa ga de ta baai wa chuushi shi、 tsugi no gairai de go soodan kudasai。" },
  "運転の仕事なので、食事は不規則で外食が多いです。運動はしていません。お酒は週2回です。": { kana: "うんてんのしごとなので、しょくじはふきそくでがいしょくがおおいです。うんどうはしていません。おさけはしゅう2かいです。", romaji: "unten no shigoto na no de、 shokuji wa fu kisoku de gaishoku ga ooi desu。 undoo wa shi te i mase n。 o sake wa shuu 2 kai desu。" },
  "重いものが乗っているような、締め付ける感じです。": { kana: "おもいものがのっているような、しめつけるかんじです。", romaji: "omoi mono ga notsu te iru yoo na、 shimetsukeru kanji desu。" },
  "階段は上れますか": { kana: "かいだんはのぼれますか", romaji: "kaidan wa nobore masu ka" },
  "頭は痛くありません。吐いてもいません。": { kana: "あたまはいたくありません。はいてもいません。", romaji: "atama wa itaku ari mase n。 hai te mo i mase n。" },
  "頭痛はありますか": { kana: "ずつうはありますか", romaji: "zutsuu wa ari masu ka" },
  "顔は動きますか": { kana: "かおはうごきますか", romaji: "kao wa ugoki masu ka" },
  "食べて15分くらいで、唇が腫れてきました。": { kana: "たべて15ふんくらいで、くちびるがはれてきました。", romaji: "tabe te 15 fun kurai de、 kuchibiru ga hare te ki mashi ta。" },
  "食べてからどのくらいで症状が出ましたか": { kana: "たべてからどのくらいでしょうじょうがでましたか", romaji: "tabe te kara dono kurai de shoojoo ga de mashi ta ka" },
  "食事のあと、急に体がかゆくなって息が苦しくなりました。": { kana: "しょくじのあと、きゅうにからだがかゆくなっていきがくるしくなりました。", romaji: "shokuji no ato、 kyuu ni karada ga kayuku natsu te iki ga kurushiku nari mashi ta。" },
  "食事は、塩分を1日6グラム未満に抑えてください。外食が続くと塩分が多くなりがちです。麺類の汁は残す、加工食品を控える、汁物は1日1杯までにする、といった工夫が役に立ちます。": { kana: "しょくじは、えんぶんを1か6ぐらむみまんにおさえてください。がいしょくがつづくとえんぶんがおおくなりがちです。めんるいのしるはのこす、かこうしょくひんをひかえる、しるものは1か1ばいまでにする、といったくふうがやくにたちます。", romaji: "shokuji wa、 enbun o 1 ka 6 guramu miman ni osae te kudasai。 gaishoku ga tsuzuku to enbun ga ooku nari gachi desu。 menrui no shiru wa nokosu、 kakoo shokuhin o hikaeru、 shirumono wa 1 ka 1 bai made ni suru、 to itsu ta kufuu ga yaku ni tachi masu。" },
  "食事はどうですか": { kana: "しょくじはどうですか", romaji: "shokuji wa doo desu ka" },
  "食事は取れていますか": { kana: "しょくじはとれていますか", romaji: "shokuji wa tore te i masu ka" },
  "食事や水分は取れていますか": { kana: "しょくじやすいぶんはとれていますか", romaji: "shokuji ya suibun wa tore te i masu ka" },
  "食事や運動の習慣を教えてください": { kana: "しょくじやうんどうのしゅうかんをおしえてください", romaji: "shokuji ya undoo no shuukan o oshie te kudasai" },
  "食欲がなくて、お粥を少しだけ。水は1日コップ3杯くらいです。": { kana: "しょくよくがなくて、おかゆをすこしだけ。みずは1かこっぷ3ばいくらいです。", romaji: "shokuyoku ga naku te、 o kayu o sukoshi dake。 mizu wa 1 ka koppu 3 bai kurai desu。" },
  "飲み込みにくさはありますか": { kana: "のみこみにくさはありますか", romaji: "nomikomi niku sa wa ari masu ka" },
  "飲み込めますか": { kana: "のみこめますか", romaji: "nomikome masu ka" },
  "飲んでいる薬はありますか": { kana: "のんでいるくすりはありますか", romaji: "non de iru kusuri wa ari masu ka" },
  "飲んでいる薬を教えてください": { kana: "のんでいるくすりをおしえてください", romaji: "non de iru kusuri o oshie te kudasai" },
  "高血圧や糖尿病はありますか": { kana: "こうけつあつやとうにょうびょうはありますか", romaji: "koo ketsuatsu ya toonyoo byoo wa ari masu ka" },
  "高齢化が進む地域では、病院へ通うこと自体が負担になる。移動手段が限られ、家族の支援も得にくい場合、通院を続けることは容易ではない。その結果、治療が必要なのに受診を控える人が増える。": { kana: "こうれいかがすすむちいきでは、びょういんへかようことじたいがふたんになる。いどうしゅだんがかぎられ、かぞくのしえんもえにくいばあい、つういんをつづけることはよういではない。そのけっか、ちりょうがひつようなのにじゅしんをひかえるひとがふえる。", romaji: "kooree ka ga susumu chiiki de wa、 byooin e kayou koto jitai ga futan ni naru。 idoo shudan ga kagira re、 kazoku no shien mo e nikui baai、 tsuuin o tsuzukeru koto wa yooi de wa nai。 sono kekka、 chiryoo ga hitsuyoo na no ni jushin o hikaeru hito ga fueru。" },
  "黄色っぽい痰がたくさん出ます。血は混じっていません。": { kana: "きいろっぽいたんがたくさんでます。ちはまじっていません。", romaji: "kiiro ppoi tan ga takusan de masu。 chi wa majitsu te i mase n。" },
};

export const CASE_OPENING_INDONESIAN: Record<string, string> = {
"朝から胸が苦しくて、冷や汗が出ます。": "Sejak pagi dada saya terasa sesak dan saya berkeringat dingin.",
"3日前から熱が出て、咳と痰が止まりません。": "Sejak tiga hari lalu saya demam, dan batuk serta dahak tidak berhenti.",
"昨日の夜からおなかが痛いです。今は右下が特に痛いです。": "Sejak tadi malam perut saya sakit. Sekarang bagian kanan bawah terutama terasa sakit.",
"今朝から心臓がドキドキして、ふらつきます。": "Sejak pagi jantung saya berdebar-debar dan saya merasa limbung.",
"家で2分くらい体が震えて、目が上を向いていました。": "Di rumah tubuh saya bergetar sekitar dua menit dan mata saya mendelik ke atas.",
"食事のあと、急に体がかゆくなって息が苦しくなりました。": "Setelah makan, tiba-tiba seluruh tubuh saya gatal dan saya sulit bernapas.",
"1か月くらい前から水をよく飲むようになり、体重が4キロ減りました。": "Sekitar sebulan ini saya jadi sering minum air dan berat badan saya turun 4 kilogram.",
"1時間前、朝食中に急に右手が動かなくなりました。": "Satu jam lalu, saat sarapan, tangan kanan saya tiba-tiba tidak bisa digerakkan.",
"昨日から少し出血があって、おなかも痛いです。": "Sejak kemarin ada sedikit perdarahan dan perut saya juga sakit.",
"昨夜から熱が出て、声をかけても返事が少なくなりました。": "Sejak tadi malam demam, dan sekarang responsnya berkurang meskipun sudah dipanggil.",
};

export function japaneseReadingFor(text: string): JapaneseReading {
  const reading = JAPANESE_READINGS[text];
  if (!reading) throw new Error(`Missing kana/romaji support for Japanese text: ${text}`);
  return {
    kana: reading.kana,
    romaji: reading.romaji
      .replaceAll('、', ',')
      .replaceAll('。', '.')
      .replace(/\s+([,.!?])/g, '$1')
      .replace(/\s+/g, ' ')
      .trim(),
  };
}
