/**
 * Reading support for Medical register B/C phrases.
 *
 * These readings are generated from authored Japanese surface forms and
 * intentionally remain a separate draft layer until a Japanese reviewer checks them.
 */

export type MedicalRegisterReading = { kana: string; romaji: string };

export const MEDICAL_REGISTER_READINGS: Record<string, MedicalRegisterReading> = {
  "1分間の息の回数": { kana: "1ふんかんのいきのかいすう", romaji: "1 funkan no iki no kaisuu" },
  "2週間以上せきが続きます": { kana: "2しゅうかんいじょうせきがつづきます", romaji: "2 shuukan ijoo seki ga tsuzuki masu" },
  "3日もお通じがありません": { kana: "3かもおつうじがありません", romaji: "3 ka mo o tsuuji ga ari mase n" },
  "MRIを受ける予定です": { kana: "MRIをうけるよていです", romaji: "MRI o ukeru yotee desu" },
  "X線で体の中の骨や肺を見る検査": { kana: "Xせんでからだのなかのほねやはいをみるけんさ", romaji: "X sen de karada no naka no hone ya hai o miru kensa" },
  "おしっこに血が混じること": { kana: "おしっこにちがまじること", romaji: "oshikko ni chi ga majiru koto" },
  "おしっこのときに痛いです": { kana: "おしっこのときにいたいです", romaji: "oshikko no toki ni itai desu" },
  "おしっこのときに痛みます": { kana: "おしっこのときにいたみます", romaji: "oshikko no toki ni itami masu" },
  "おしっこのとき痛くて熱があります": { kana: "おしっこのときいたくてねつがあります", romaji: "oshikko no toki itaku te netsu ga ari masu" },
  "おしっこの道に細菌が入る病気": { kana: "おしっこのみちにさいきんがはいるびょうき", romaji: "oshikko no michi ni saikin ga hairu byooki" },
  "おしっこをするときに痛むこと": { kana: "おしっこをするときにいたむこと", romaji: "oshikko o suru toki ni itamu koto" },
  "おしっこを調べる検査": { kana: "おしっこをしらべるけんさ", romaji: "oshikko o shiraberu kensa" },
  "おなかがシクシク痛みます": { kana: "おなかがしくしくいたみます", romaji: "onaka ga shikushiku itami masu" },
  "おなかが張ってズボンがきついです": { kana: "おなかがはってずぼんがきついです", romaji: "onaka ga hatsu te zubon ga kitsui desu" },
  "おなかが張って苦しいです": { kana: "おなかがはってくるしいです", romaji: "onaka ga hatsu te kurushii desu" },
  "おなかが張る感じ": { kana: "おなかがはるかんじ", romaji: "onaka ga haru kanji" },
  "おなかが痛い状態": { kana: "おなかがいたいじょうたい", romaji: "onaka ga itai jootai" },
  "おなかが痛くて下痢が続きます": { kana: "おなかがいたくてげりがつづきます", romaji: "onaka ga itaku te geri ga tsuzuki masu" },
  "おなかのエコーを受けました": { kana: "おなかのえこーをうけました", romaji: "onaka no ekoo o uke mashi ta" },
  "おなかの中に水がたまること": { kana: "おなかのなかにみずがたまること", romaji: "onaka no naka ni mizu ga tamaru koto" },
  "おなかを触られると痛いです": { kana: "おなかをさわられるといたいです", romaji: "onaka o sawara reru to itai desu" },
  "お尻から入れて使う薬": { kana: "おしりからいれてつかうくすり", romaji: "o shiri kara ire te tsukau kusuri" },
  "お尻から入れる薬": { kana: "おしりからいれるくすり", romaji: "o shiri kara ireru kusuri" },
  "お薬手帳を持ってきました": { kana: "おくすりてちょうをもってきました", romaji: "o kusuri techoo o motsu te ki mashi ta" },
  "かゆい感じ": { kana: "かゆいかんじ", romaji: "kayui kanji" },
  "かゆくて赤いふくらみが出ます": { kana: "かゆくてあかいふくらみがでます", romaji: "kayuku te akai fukurami ga de masu" },
  "くらくらして立てません": { kana: "くらくらしてたてません", romaji: "kurakura shi te tate mase n" },
  "けいれんを繰り返す病気": { kana: "けいれんをくりかえすびょうき", romaji: "keeren o kurikaesu byooki" },
  "けいれんを起こして倒れました": { kana: "けいれんをおこしてたおれました", romaji: "keeren o okoshi te taore mashi ta" },
  "この軟膏をどこに塗りますか": { kana: "このなんこうをどこにぬりますか", romaji: "kono nankoo o doko ni nuri masu ka" },
  "この部分が赤くなっています": { kana: "このぶぶんがあかくなっています", romaji: "kono bubun ga akaku natsu te i masu" },
  "すぐに行う手術": { kana: "すぐにおこなうしゅじゅつ", romaji: "sugu ni okonau shujutsu" },
  "せきが2週間止まりません": { kana: "せきが2しゅうかんとまりません", romaji: "seki ga 2 shuukan tomari mase n" },
  "せきが出ること": { kana: "せきがでること", romaji: "seki ga deru koto" },
  "せきと一緒に血が出ること": { kana: "せきといっしょにちがでること", romaji: "seki to issho ni chi ga deru koto" },
  "せきをしたら血が出ました": { kana: "せきをしたらちがでました", romaji: "seki o shi tara chi ga de mashi ta" },
  "そばを食べると息苦しくなります": { kana: "そばをたべるといきぐるしくなります", romaji: "soba o taberu to ikigurushiku nari masu" },
  "たまった膿を出すために切開する処置": { kana: "たまったうみをだすためにせっかいするしょち", romaji: "tamatsu ta umi o dasu tame ni sekkai suru shochi" },
  "どうして順番が後になるのですか": { kana: "どうしてじゅんばんがあとになるのですか", romaji: "doo shi te junban ga ato ni naru no desu ka" },
  "どのくらい細かいものが見えるか調べる検査": { kana: "どのくらいこまかいものがみえるかしらべるけんさ", romaji: "dono kurai komakai mono ga mieru ka shiraberu kensa" },
  "のどが痛い状態": { kana: "のどがいたいじょうたい", romaji: "nodo ga itai jootai" },
  "のどが痛くて飲み込みにくいです": { kana: "のどがいたくてのみこみにくいです", romaji: "nodo ga itaku te nomikomi nikui desu" },
  "のどが痛くて鼻水が出ます": { kana: "のどがいたくてはなみずがでます", romaji: "nodo ga itaku te hanamizu ga de masu" },
  "はれ": { kana: "はれ", romaji: "hare" },
  "ばい菌を抑える薬を飲みます": { kana: "ばいきんをおさえるくすりをのみます", romaji: "baikin o osaeru kusuri o nomi masu" },
  "みぞおちが痛みます": { kana: "みぞおちがいたみます", romaji: "mizoochi ga itami masu" },
  "むくみ": { kana: "むくみ", romaji: "mukumi" },
  "ろれつが回りにくく、話しにくい状態": { kana: "ろれつがまわりにくく、はなしにくいじょうたい", romaji: "roretsu ga mawari nikuku、 hanashi nikui jootai" },
  "アレルギーで体全体に強い症状が出ること": { kana: "あれるぎーでたいぜんたいにつよいしょうじょうがでること", romaji: "arerugii de tai zentai ni tsuyoi shoojoo ga deru koto" },
  "アレルギーによるかゆみや鼻水を抑える薬": { kana: "あれるぎーによるかゆみやはなみずをおさえるくすり", romaji: "arerugii ni yoru kayumi ya hanamizu o osaeru kusuri" },
  "アレルギーの強い反応を止める注射薬": { kana: "あれるぎーのつよいはんのうをとめるちゅうしゃやく", romaji: "arerugii no tsuyoi hannoo o tomeru chuusha yaku" },
  "インスリンを打っています": { kana: "いんすりんをうっています", romaji: "insurin o utsu te i masu" },
  "ウイルスの増えるのを抑える薬": { kana: "ういるすのふえるのをおさえるくすり", romaji: "uirusu no fueru no o osaeru kusuri" },
  "カビや真菌を抑える薬": { kana: "かびやしんきんをおさえるくすり", romaji: "kabi ya shinkin o osaeru kusuri" },
  "トイレが近いです": { kana: "といれがちかいです", romaji: "toire ga chikai desu" },
  "トイレが近くなること": { kana: "といれがちかくなること", romaji: "toire ga chikaku naru koto" },
  "トイレで血が出ました": { kana: "といれでちがでました", romaji: "toire de chi ga de mashi ta" },
  "レントゲンを撮りました": { kana: "れんとげんをとりました", romaji: "rentogen o tori mashi ta" },
  "一時的に意識を失って倒れること": { kana: "いちじてきにいしきをうしなってたおれること", romaji: "ichiji teki ni ishiki o ushinatsu te taoreru koto" },
  "一時的に気を失うこと": { kana: "いちじてきにきをうしなうこと", romaji: "ichiji teki ni ki o ushinau koto" },
  "丸い薬": { kana: "まるいくすり", romaji: "marui kusuri" },
  "乳房の状態をX線で調べる検査": { kana: "ちぶさのじょうたいをXせんでしらべるけんさ", romaji: "chibusa no jootai o X sen de shiraberu kensa" },
  "他の病院に診てもらうための手紙": { kana: "ほかのびょういんにみてもらうためのてがみ", romaji: "hoka no byooin ni mi te morau tame no tegami" },
  "体がだるい感じ": { kana: "からだがだるいかんじ", romaji: "karada ga darui kanji" },
  "体がだるくて何もする気になれません": { kana: "からだがだるくてなんもするきになれません", romaji: "karada ga daruku te nan mo suru ki ni nare mase n" },
  "体がだるくて動けません": { kana: "からだがだるくてうごけません", romaji: "karada ga daruku te ugoke mase n" },
  "体がだるくて疲れやすい感じ": { kana: "からだがだるくてつかれやすいかんじ", romaji: "karada ga daruku te tsukare yasui kanji" },
  "体が勝手に震えました": { kana: "からだがかってにふるえました", romaji: "karada ga katte ni furue mashi ta" },
  "体が強く反応しすぎること": { kana: "からだがつよくはんのうしすぎること", romaji: "karada ga tsuyoku hannoo shi sugiru koto" },
  "体に余分な水分がたまってむくむこと": { kana: "からだによぶんなすいぶんがたまってむくむこと", romaji: "karada ni yobun na suibun ga tamatsu te mukumu koto" },
  "体の一部を少し採って詳しく調べる検査": { kana: "からだのいちぶをすこしとってくわしくしらべるけんさ", romaji: "karada no ichibu o sukoshi totsu te kuwashiku shiraberu kensa" },
  "体の中の血や液を外に出す管": { kana: "からだのなかのちやえきをそとにだすくだ", romaji: "karada no naka no chi ya eki o soto ni dasu kuda" },
  "体の中を輪切りにして写す検査": { kana: "からだのなかをわぎりにしてうつすけんさ", romaji: "karada no naka o wagiri ni shi te utsusu kensa" },
  "体の水分が足りない状態": { kana: "からだのすいぶんがたりないじょうたい", romaji: "karada no suibun ga tari nai jootai" },
  "体の熱": { kana: "からだのねつ", romaji: "karada no netsu" },
  "体の片側がピリピリ痛みます": { kana: "からだのかたがわがぴりぴりいたみます", romaji: "karada no katagawa ga piripiri itami masu" },
  "体を切って治療すること": { kana: "からだをきってちりょうすること", romaji: "karada o kitsu te chiryoo suru koto" },
  "体中に赤いぶつぶつが出ました": { kana: "たいちゅうにあかいぶつぶつがでました", romaji: "tai chuu ni akai butsubutsu ga de mashi ta" },
  "体重が減ること": { kana: "たいじゅうがへること", romaji: "taijuu ga heru koto" },
  "何回も吐いています": { kana: "なんかいもはいています", romaji: "nan kai mo hai te i masu" },
  "何度もトイレに行きたくなります": { kana: "なんどもといれにいきたくなります", romaji: "nan do mo toire ni iki taku nari masu" },
  "何度も吐いてしまいました": { kana: "なんどもはいてしまいました", romaji: "nan do mo hai te shimai mashi ta" },
  "何日も便が出ません": { kana: "なんにちもびんがでません", romaji: "nan nichi mo bin ga de mase n" },
  "余分な水分を尿として出す薬": { kana: "よぶんなすいぶんをにょうとしてだすくすり", romaji: "yobun na suibun o nyoo to shi te dasu kusuri" },
  "便が出にくいこと": { kana: "びんがでにくいこと", romaji: "bin ga de nikui koto" },
  "便が出にくい状態": { kana: "びんがでにくいじょうたい", romaji: "bin ga de nikui jootai" },
  "便に目に見えない血が混じっていないか調べる検査": { kana: "びんにめにみえないちがまじっていないかしらべるけんさ", romaji: "bin ni me ni mie nai chi ga majitsu te i nai ka shiraberu kensa" },
  "便に血が混じること": { kana: "びんにちがまじること", romaji: "bin ni chi ga majiru koto" },
  "便を出しやすくする薬": { kana: "びんをだしやすくするくすり", romaji: "bin o dashi yasuku suru kusuri" },
  "便を調べる検査": { kana: "びんをしらべるけんさ", romaji: "bin o shiraberu kensa" },
  "便器が赤くなるくらい血が出ました": { kana: "べんきがあかくなるくらいちがでました", romaji: "benki ga akaku naru kurai chi ga de mashi ta" },
  "倒れて意識がありませんでした": { kana: "たおれていしきがありませんでした", romaji: "taore te ishiki ga ari mase n deshi ta" },
  "傷の端を糸で閉じる処置": { kana: "きずのはしをいとでとじるしょち", romaji: "kizu no hashi o ito de tojiru shochi" },
  "傷を何針か縫いました": { kana: "きずをなんはりかぬいました", romaji: "kizu o nan hari ka nui mashi ta" },
  "傷を洗って保護する処置": { kana: "きずをあらってほごするしょち", romaji: "kizu o aratsu te hogo suru shochi" },
  "傷を糸で閉じること": { kana: "きずをいとでとじること", romaji: "kizu o ito de tojiru koto" },
  "光を見ると頭が痛くなります": { kana: "ひかりをみるとあたまがいたくなります", romaji: "hikari o miru to atama ga itaku nari masu" },
  "入院している人が過ごす部屋": { kana: "にゅういんしているひとがすごすへや", romaji: "nyuuin shi te iru hito ga sugosu heya" },
  "入院することになりました": { kana: "にゅういんすることになりました", romaji: "nyuuin suru koto ni nari mashi ta" },
  "入院できる病棟やベッドを手配すること": { kana: "にゅういんできるびょうとうやべっどをてはいすること", romaji: "nyuuin dekiru byootoo ya beddo o tehai suru koto" },
  "全身がかゆいです": { kana: "ぜんしんがかゆいです", romaji: "zenshin ga kayui desu" },
  "冬に流行るウイルスの病気": { kana: "ふゆにはやるういるすのびょうき", romaji: "fuyu ni hayaru uirusu no byooki" },
  "冷や汗が出て手が震えます": { kana: "ひやあせがでててがふるえます", romaji: "hiyaase ga de te te ga furue masu" },
  "処置する場所だけを痛くなくする麻酔": { kana: "しょちするばしょだけをいたくなくするますい", romaji: "shochi suru basho dake o itaku naku suru masui" },
  "処置に同意したことを示す書類": { kana: "しょちにどういしたことをしめすしょるい", romaji: "shochi ni dooi shi ta koto o shimesu shorui" },
  "処置の間、痛みを感じないようにすること": { kana: "しょちのあいだ、いたみをかんじないようにすること", romaji: "shochi no aida、 itami o kanji nai yoo ni suru koto" },
  "別の病院や専門医に診てもらうための手紙": { kana: "べつのびょういんやせんもんいにみてもらうためのてがみ", romaji: "betsu no byooin ya senmon i ni mi te morau tame no tegami" },
  "力が入りません": { kana: "ちからがはいりません", romaji: "chikara ga hairi mase n" },
  "動きや話す力を取り戻すための訓練": { kana: "うごきやはなすちからをとりもどすためのくんれん", romaji: "ugoki ya hanasu chikara o torimodosu tame no kunren" },
  "危険な不整脈を電気で止める機械": { kana: "きけんなふせいみゃくをでんきでとめるきかい", romaji: "kiken na fusee myaku o denki de tomeru kikai" },
  "受診のときに出すカード": { kana: "じゅしんのときにだすかーど", romaji: "jushin no toki ni dasu kaado" },
  "受診の日時を決めること": { kana: "じゅしんのにちじをきめること", romaji: "jushin no nichiji o kimeru koto" },
  "口からカメラを入れて食道や胃を見る検査": { kana: "くちからかめらをいれてしょくどうやいをみるけんさ", romaji: "kuchi kara kamera o ire te shokudoo ya i o miru kensa" },
  "口から管を入れて息を助けること": { kana: "くちからくだをいれていきをたすけること", romaji: "kuchi kara kuda o ire te iki o tasukeru koto" },
  "口が渇いて尿が少ないです": { kana: "くちがかわいてにょうがすくないです", romaji: "kuchi ga kawai te nyoo ga sukunai desu" },
  "右の肋骨の下が痛いです": { kana: "みぎのあばらぼねのしたがいたいです", romaji: "migi no abarabone no shita ga itai desu" },
  "右下のおなかが痛いです": { kana: "みぎしたのおなかがいたいです", romaji: "migishita no onaka ga itai desu" },
  "右手と右足に力が入りません": { kana: "みぎてとみぎあしにちからがはいりません", romaji: "migite to migiashi ni chikara ga hairi mase n" },
  "吐いたものに血が混じること": { kana: "はいたものにちがまじること", romaji: "hai ta mono ni chi ga majiru koto" },
  "吐いてしまうこと": { kana: "はいてしまうこと", romaji: "hai te shimau koto" },
  "吐きそうな感じ": { kana: "はきそうなかんじ", romaji: "haki soo na kanji" },
  "吐き気がします": { kana: "はきけがします", romaji: "hakike ga shi masu" },
  "吐き気や嘔吐を抑える薬": { kana: "はきけやおうとをおさえるくすり", romaji: "hakike ya ooto o osaeru kusuri" },
  "吸って使う薬": { kana: "すってつかうくすり", romaji: "sutsu te tsukau kusuri" },
  "吸入器を使っています": { kana: "きゅうにゅうきをつかっています", romaji: "kyuunyuu ki o tsukatsu te i masu" },
  "味が分かりません": { kana: "あじがわかりません", romaji: "aji ga wakari mase n" },
  "呼びかけても反応が鈍いです": { kana: "よびかけてもはんのうがにぶいです", romaji: "yobikake te mo hannoo ga nibui desu" },
  "呼びかけても返事がありません": { kana: "よびかけてもへんじがありません", romaji: "yobikake te mo henji ga ari mase n" },
  "呼吸や心臓が止まったときに行う救命処置": { kana: "こきゅうやしんぞうがとまったときにおこなうきゅうめいしょち", romaji: "kokyuu ya shinzoo ga tomatsu ta toki ni okonau kyuumee shochi" },
  "呼吸を助けるために気管に管を入れる処置": { kana: "こきゅうをたすけるためにきかんにくだをいれるしょち", romaji: "kokyuu o tasukeru tame ni kikan ni kuda o ireru shochi" },
  "呼吸を助ける機械": { kana: "こきゅうをたすけるきかい", romaji: "kokyuu o tasukeru kikai" },
  "唇が青っぽくなっています": { kana: "くちびるがあおっぽくなっています", romaji: "kuchibiru ga ao ppoku natsu te i masu" },
  "唇や指の先が青紫色になること": { kana: "くちびるやゆびのさきがあおむらさきいろになること", romaji: "kuchibiru ya yubi no saki ga aomurasaki iro ni naru koto" },
  "唇や指先が青紫色になること": { kana: "くちびるやゆびさきがあおむらさきいろになること", romaji: "kuchibiru ya yubisaki ga aomurasaki iro ni naru koto" },
  "坐薬を使ったことがあります": { kana: "ざやくをつかったことがあります", romaji: "zayaku o tsukatsu ta koto ga ari masu" },
  "声がかすれて出しにくいです": { kana: "こえがかすれてだしにくいです", romaji: "koe ga kasure te dashi nikui desu" },
  "声がかすれること": { kana: "こえがかすれること", romaji: "koe ga kasureru koto" },
  "夜、汗でパジャマが濡れます": { kana: "よる、あせでぱじゃまがぬれます", romaji: "yoru、 ase de pajama ga nure masu" },
  "夜中にゼーゼーして息苦しいです": { kana: "よなかにぜーぜーしていきぐるしいです", romaji: "yonaka ni zeezee shi te ikigurushii desu" },
  "夜中に咳が止まりません": { kana: "よなかにせきがとまりません", romaji: "yonaka ni seki ga tomari mase n" },
  "夜中に息が苦しくなって起きます": { kana: "よなかにいきがくるしくなっておきます", romaji: "yonaka ni iki ga kurushiku natsu te oki masu" },
  "夜中に息苦しくて目が覚めること": { kana: "よなかにいきぐるしくてめがさめること", romaji: "yonaka ni ikigurushiku te me ga sameru koto" },
  "大腸カメラを受けました": { kana: "だいちょうかめらをうけました", romaji: "daichoo kamera o uke mashi ta" },
  "太い血管に入れる点滴の管": { kana: "ふといけっかんにいれるてんてきのくだ", romaji: "futoi kekkan ni ireru tenteki no kuda" },
  "太ももに注射を打たれました": { kana: "ふとももにちゅうしゃをうたれました", romaji: "futomomo ni chuusha o uta re mashi ta" },
  "妊娠している可能性があるか調べる検査": { kana: "にんしんしているかのうせいがあるかしらべるけんさ", romaji: "ninshin shi te iru kanoo see ga aru ka shiraberu kensa" },
  "寒くてガタガタ震えました": { kana: "さむくてがたがたふるえました", romaji: "samuku te gatagata furue mashi ta" },
  "寒く感じて震えること": { kana: "さむくかんじてふるえること", romaji: "samuku kanji te furueru koto" },
  "寒気がして意識がぼんやりします": { kana: "かんきがしていしきがぼんやりします", romaji: "kanki ga shi te ishiki ga bonyari shi masu" },
  "寝ている間に汗をかくこと": { kana: "ねているあいだにあせをかくこと", romaji: "ne te iru aida ni ase o kaku koto" },
  "専門の先生に診てもらうこと": { kana: "せんもんのせんせいにみてもらうこと", romaji: "senmon no sensee ni mi te morau koto" },
  "小さな粒状になっている薬": { kana: "ちいさなつぶじょうになっているくすり", romaji: "chiisana tsubu joo ni natsu te iru kusuri" },
  "小型の機械で一日中心電図を記録する検査": { kana: "こがたのきかいでいちにちちゅうしんでんずをきろくするけんさ", romaji: "kogata no kikai de ichi nichi chuushin den zu o kiroku suru kensa" },
  "少し動くだけで息が切れます": { kana: "すこしうごくだけでいきがきれます", romaji: "sukoshi ugoku dake de iki ga kire masu" },
  "尿がしたいのに出ません": { kana: "にょうがしたいのにでません", romaji: "nyoo ga shi tai no ni de mase n" },
  "尿が赤いです": { kana: "にょうがあかいです", romaji: "nyoo ga akai desu" },
  "尿が赤くなりました": { kana: "にょうがあかくなりました", romaji: "nyoo ga akaku nari mashi ta" },
  "尿に血が混じること": { kana: "にょうにちがまじること", romaji: "nyoo ni chi ga majiru koto" },
  "尿の管を入れますか": { kana: "にょうのくだをいれますか", romaji: "nyoo no kuda o ire masu ka" },
  "尿をするときの痛み": { kana: "にょうをするときのいたみ", romaji: "nyoo o suru toki no itami" },
  "尿を出したいのに出せない状態": { kana: "にょうをだしたいのにだせないじょうたい", romaji: "nyoo o dashi tai no ni dase nai jootai" },
  "尿を出しやすくする薬": { kana: "にょうをだしやすくするくすり", romaji: "nyoo o dashi yasuku suru kusuri" },
  "尿を出すための細い管": { kana: "にょうをだすためのほそいくだ", romaji: "nyoo o dasu tame no hosoi kuda" },
  "強い磁石を使って体の中を詳しく見る検査": { kana: "つよいじしゃくをつかってからだのなかをくわしくみるけんさ", romaji: "tsuyoi jishaku o tsukatsu te karada no naka o kuwashiku miru kensa" },
  "心臓がドキドキします": { kana: "しんぞうがどきどきします", romaji: "shinzoo ga dokidoki shi masu" },
  "心臓がドキドキする感じ": { kana: "しんぞうがどきどきするかんじ", romaji: "shinzoo ga dokidoki suru kanji" },
  "心臓が十分に血液を送れなくなった状態": { kana: "しんぞうがじゅうぶんにけつえきをおくれなくなったじょうたい", romaji: "shinzoo ga juubun ni ketsueki o okure naku natsu ta jootai" },
  "心臓と呼吸を助ける処置": { kana: "しんぞうとこきゅうをたすけるしょち", romaji: "shinzoo to kokyuu o tasukeru shochi" },
  "心臓に血液を送る血管が詰まる病気": { kana: "しんぞうにけつえきをおくるけっかんがつまるびょうき", romaji: "shinzoo ni ketsueki o okuru kekkan ga tsumaru byooki" },
  "心臓のエコーを受けました": { kana: "しんぞうのえこーをうけました", romaji: "shinzoo no ekoo o uke mashi ta" },
  "心臓のリズムが不規則になる不整脈": { kana: "しんぞうのりずむがふきそくになるふせいみゃく", romaji: "shinzoo no rizumu ga fu kisoku ni naru fusee myaku" },
  "心臓の筋肉が傷ついたときに出る物質": { kana: "しんぞうのきんにくがきずついたときにでるぶっしつ", romaji: "shinzoo no kinniku ga kizutsui ta toki ni deru busshitsu" },
  "心臓の血管が一時的に狭くなる病気": { kana: "しんぞうのけっかんがいちじてきにせまくなるびょうき", romaji: "shinzoo no kekkan ga ichiji teki ni semaku naru byooki" },
  "心臓の電気の流れを記録する検査": { kana: "しんぞうのでんきのながれをきろくするけんさ", romaji: "shinzoo no denki no nagare o kiroku suru kensa" },
  "心臓の音に雑音が聞こえること": { kana: "しんぞうのおとにざつおんがきこえること", romaji: "shinzoo no oto ni zatsuon ga kikoeru koto" },
  "心臓の鼓動が強く感じること": { kana: "しんぞうのこどうがつよくかんじること", romaji: "shinzoo no kodoo ga tsuyoku kanjiru koto" },
  "急な病気のときに呼ぶ車": { kana: "きゅうなびょうきのときによぶくるま", romaji: "kyuu na byooki no toki ni yobu kuruma" },
  "急な病気のときに行くところ": { kana: "きゅうなびょうきのときにいくところ", romaji: "kyuu na byooki no toki ni iku tokoro" },
  "急に体がガタガタ震えました": { kana: "きゅうにからだががたがたふるえました", romaji: "kyuu ni karada ga gatagata furue mashi ta" },
  "急に右手が動かなくなりました": { kana: "きゅうにみぎてがうごかなくなりました", romaji: "kyuu ni migite ga ugoka naku nari mashi ta" },
  "急に強く震えること": { kana: "きゅうにつよくふるえること", romaji: "kyuu ni tsuyoku furueru koto" },
  "急に意識がなくなって倒れました": { kana: "きゅうにいしきがなくなってたおれました", romaji: "kyuu ni ishiki ga nakunatsu te taore mashi ta" },
  "急に熱が出て関節が痛いです": { kana: "きゅうにねつがでてかんせつがいたいです", romaji: "kyuu ni netsu ga de te kansetsu ga itai desu" },
  "急に胸が痛くて息ができません": { kana: "きゅうにむねがいたくていきができません", romaji: "kyuu ni mune ga itaku te iki ga deki mase n" },
  "息ができなくなること": { kana: "いきができなくなること", romaji: "iki ga deki naku naru koto" },
  "息が苦しいです": { kana: "いきがくるしいです", romaji: "iki ga kurushii desu" },
  "息が苦しい状態": { kana: "いきがくるしいじょうたい", romaji: "iki ga kurushii jootai" },
  "息と一緒に吸い込む薬": { kana: "いきといっしょにすいこむくすり", romaji: "iki to issho ni suikomu kusuri" },
  "息をするときにヒューヒュー音がすること": { kana: "いきをするときにひゅーひゅーおとがすること", romaji: "iki o suru toki ni hyuuhyuu oto ga suru koto" },
  "息をするとゼーゼーします": { kana: "いきをするとぜーぜーします", romaji: "iki o suru to zeezee shi masu" },
  "息をするとヒューヒューします": { kana: "いきをするとひゅーひゅーします", romaji: "iki o suru to hyuuhyuu shi masu" },
  "息を吸ったり吐いたりして肺の働きを調べる検査": { kana: "いきをすったりはいたりしてはいのはたらきをしらべるけんさ", romaji: "iki o sutsu tari hai tari shi te hai no hataraki o shiraberu kensa" },
  "息苦しい状態": { kana: "いきぐるしいじょうたい", romaji: "ikigurushii jootai" },
  "意識がはっきりしない状態": { kana: "いしきがはっきりしないじょうたい", romaji: "ishiki ga hakkiri shi nai jootai" },
  "意識がぼんやりしたり反応が悪くなったりする状態": { kana: "いしきがぼんやりしたりはんのうがわるくなったりするじょうたい", romaji: "ishiki ga bonyari shi tari hannoo ga waruku natsu tari suru jootai" },
  "感染が全身に広がった危険な状態": { kana: "かんせんがぜんしんにひろがったきけんなじょうたい", romaji: "kansen ga zenshin ni hirogatsu ta kiken na jootai" },
  "感覚が鈍く、ピリピリする感じ": { kana: "かんかくがにぶく、ぴりぴりするかんじ", romaji: "kankaku ga nibuku、 piripiri suru kanji" },
  "手で触って状態を確認する診察": { kana: "てでさわってじょうたいをかくにんするしんさつ", romaji: "te de sawatsu te jootai o kakunin suru shinsatsu" },
  "手の先がしびれます": { kana: "てのさきがしびれます", romaji: "te no saki ga shibire masu" },
  "手の先がジンジンします": { kana: "てのさきがじんじんします", romaji: "te no saki ga jinjin shi masu" },
  "手術を受ける予定です": { kana: "しゅじゅつをうけるよていです", romaji: "shujutsu o ukeru yotee desu" },
  "手足などが動かしにくくなること": { kana: "てあしなどがうごかしにくくなること", romaji: "teashi nado ga ugokashi nikuku naru koto" },
  "手足の力や感覚を調べました": { kana: "てあしのちからやかんかくをしらべました", romaji: "teashi no chikara ya kankaku o shirabe mashi ta" },
  "指にはさむ機械をつけられました": { kana: "ゆびにはさむきかいをつけられました", romaji: "yubi ni hasamu kikai o tsuke rare mashi ta" },
  "採血されました": { kana: "さいけつされました", romaji: "saiketsu sa re mashi ta" },
  "放射線で体の中を写す検査": { kana: "ほうしゃせんでからだのなかをうつすけんさ", romaji: "hoosha sen de karada no naka o utsusu kensa" },
  "救急車などで病院へ運ぶこと": { kana: "きゅうきゅうしゃなどでびょういんへはこぶこと", romaji: "kyuukyuu sha nado de byooin e hakobu koto" },
  "救急車を呼んだほうがいいですか": { kana: "きゅうきゅうしゃをよんだほうがいいですか", romaji: "kyuukyuu sha o yon da hoo ga ii desu ka" },
  "新型コロナウイルスの感染症": { kana: "しんがたころなういるすのかんせんしょう", romaji: "shingata korona uirusu no kansen shoo" },
  "日付や場所が分からなくなります": { kana: "ひづけやばしょがわからなくなります", romaji: "hizuke ya basho ga wakara naku nari masu" },
  "時間や場所、人が分からなくなる状態": { kana: "じかんやばしょ、ひとがわからなくなるじょうたい", romaji: "jikan ya basho、 hito ga wakara naku naru jootai" },
  "検査や治療に同意したことを確認する書類": { kana: "けんさやちりょうにどういしたことをかくにんするしょるい", romaji: "kensa ya chiryoo ni dooi shi ta koto o kakunin suru shorui" },
  "横になると息が苦しくなること": { kana: "よこになるといきがくるしくなること", romaji: "yoko ni naru to iki ga kurushiku naru koto" },
  "横になると息苦しくなります": { kana: "よこになるといきぐるしくなります", romaji: "yoko ni naru to ikigurushiku nari masu" },
  "横になると苦しくて、起きていると楽です": { kana: "よこになるとくるしくて、おきているとらくです", romaji: "yoko ni naru to kurushiku te、 oki te iru to raku desu" },
  "機械で血液から余分な水分や老廃物を取り除く治療": { kana: "きかいでけつえきからよぶんなすいぶんやろうはいぶつをとりのぞくちりょう", romaji: "kikai de ketsueki kara yobun na suibun ya roohai butsu o torinozoku chiryoo" },
  "歩くと胸が苦しくなり、休むと治まります": { kana: "あるくとむねがくるしくなり、やすむとおさまります", romaji: "aruku to mune ga kurushiku nari、 yasumu to osamari masu" },
  "毎日リハビリを受けています": { kana: "まいにちりはびりをうけています", romaji: "mainichi rihabiri o uke te i masu" },
  "気が遠くなって倒れました": { kana: "きがとおくなってたおれました", romaji: "ki ga tooku natsu te taore mashi ta" },
  "気を失いそうになること": { kana: "きをうしないそうになること", romaji: "ki o ushinai soo ni naru koto" },
  "気を失うこと": { kana: "きをうしなうこと", romaji: "ki o ushinau koto" },
  "気持ちが悪くて吐きそうです": { kana: "きもちがわるくてはきそうです", romaji: "kimochi ga waruku te haki soo desu" },
  "気管支に炎症が起きる病気": { kana: "きかんしにえんしょうがおきるびょうき", romaji: "kikan shi ni enshoo ga okiru byooki" },
  "気道が狭くなって息が苦しくなる病気": { kana: "きどうがせまくなっていきがくるしくなるびょうき", romaji: "kidoo ga semaku natsu te iki ga kurushiku naru byooki" },
  "水っぽい便が何度も出ること": { kana: "みずっぽいびんがなんどもでること", romaji: "mizu ppoi bin ga nan do mo deru koto" },
  "水のような便が何回も出ます": { kana: "みずのようなびんがなんかいもでます", romaji: "mizu no yoo na bin ga nan kai mo de masu" },
  "水のような便が続いています": { kana: "みずのようなびんがつづいています", romaji: "mizu no yoo na bin ga tsuzui te i masu" },
  "水のような鼻水が出ます": { kana: "みずのようなはなみずがでます", romaji: "mizu no yoo na hanamizu ga de masu" },
  "水分が取れず、尿も少ないです": { kana: "すいぶんがとれず、にょうもすくないです", romaji: "suibun ga tore zu、 nyoo mo sukunai desu" },
  "決められた治療を続けられているかということ": { kana: "きめられたちりょうをつづけられているかということ", romaji: "kime rare ta chiryoo o tsuzuke rare te iru ka to yuu koto" },
  "注射針で薬を入れること": { kana: "ちゅうしゃはりでくすりをいれること", romaji: "chuusha hari de kusuri o ireru koto" },
  "炎症やアレルギーを抑える薬": { kana: "えんしょうやあれるぎーをおさえるくすり", romaji: "enshoo ya arerugii o osaeru kusuri" },
  "炎症を強く抑える薬": { kana: "えんしょうをつよくおさえるくすり", romaji: "enshoo o tsuyoku osaeru kusuri" },
  "点滴ではなく注射で薬を入れました": { kana: "てんてきではなくちゅうしゃでくすりをいれました", romaji: "tenteki de wa naku chuusha de kusuri o ire mashi ta" },
  "熱があります。体がだるいです": { kana: "ねつがあります。からだがだるいです", romaji: "netsu ga ari masu。 karada ga darui desu" },
  "熱が出ている状態": { kana: "ねつがでているじょうたい", romaji: "netsu ga de te iru jootai" },
  "熱が続いて息が苦しいです": { kana: "ねつがつづいていきがくるしいです", romaji: "netsu ga tsuzui te iki ga kurushii desu" },
  "熱っぽい感じがします": { kana: "ねつっぽいかんじがします", romaji: "netsu ppoi kanji ga shi masu" },
  "熱を下げる薬": { kana: "ねつをさげるくすり", romaji: "netsu o sageru kusuri" },
  "片方の耳が聞こえにくいです": { kana: "かたほうのみみがきこえにくいです", romaji: "katahoo no mimi ga kikoe nikui desu" },
  "片頭痛の発作を止める薬": { kana: "かたずつうのほっさをとめるくすり", romaji: "kata zutsuu no hossa o tomeru kusuri" },
  "生理ではないのに出血があります": { kana: "せいりではないのにしゅっけつがあります", romaji: "seeri de wa nai no ni shukketsu ga ari masu" },
  "生理のときに強い痛みが出る病気": { kana: "せいりのときにつよいいたみがでるびょうき", romaji: "seeri no toki ni tsuyoi itami ga deru byooki" },
  "生理以外の時期に出血すること": { kana: "せいりいがいのじきにしゅっけつすること", romaji: "seeri igai no jiki ni shukketsu suru koto" },
  "生理痛がひどくて動けません": { kana: "せいりつうがひどくてうごけません", romaji: "seeri tsuu ga hidoku te ugoke mase n" },
  "病原体の一部を短時間で調べる検査": { kana: "びょうげんたいのいちぶをたんじかんでしらべるけんさ", romaji: "byoogen tai no ichibu o tan jikan de shiraberu kensa" },
  "病気の内容を証明する書類": { kana: "びょうきのないようをしょうめいするしょるい", romaji: "byooki no naiyoo o shoomee suru shorui" },
  "病院から帰れること": { kana: "びょういんからかえれること", romaji: "byooin kara kaereru koto" },
  "病院に泊まって治療すること": { kana: "びょういんにとまってちりょうすること", romaji: "byooin ni tomatsu te chiryoo suru koto" },
  "症状が出たときだけ飲む薬": { kana: "しょうじょうがでたときだけのむくすり", romaji: "shoojoo ga de ta toki dake nomu kusuri" },
  "痛いときだけ飲む薬はありますか": { kana: "いたいときだけのむくすりはありますか", romaji: "itai toki dake nomu kusuri wa ari masu ka" },
  "痛みをやわらげる薬": { kana: "いたみをやわらげるくすり", romaji: "itami o yawarageru kusuri" },
  "白目が黄色く見えます": { kana: "しろめがきいろくみえます", romaji: "shirome ga kiiroku mie masu" },
  "皮膚が赤くなること": { kana: "ひふがあかくなること", romaji: "hifu ga akaku naru koto" },
  "皮膚が赤く盛り上がってかゆくなる症状": { kana: "ひふがあかくもりあがってかゆくなるしょうじょう", romaji: "hifu ga akaku moriagatsu te kayuku naru shoojoo" },
  "皮膚に塗る油性の薬": { kana: "ひふにぬるゆせいのくすり", romaji: "hifu ni nuru yusee no kusuri" },
  "皮膚に塗る薬": { kana: "ひふにぬるくすり", romaji: "hifu ni nuru kusuri" },
  "皮膚に貼って使う薬": { kana: "ひふにはってつかうくすり", romaji: "hifu ni hatsu te tsukau kusuri" },
  "皮膚に赤いぶつぶつが出ること": { kana: "ひふにあかいぶつぶつがでること", romaji: "hifu ni akai butsubutsu ga deru koto" },
  "皮膚に赤いぶつぶつなどが出ること": { kana: "ひふにあかいぶつぶつなどがでること", romaji: "hifu ni akai butsubutsu nado ga deru koto" },
  "皮膚や白目が黄色くなること": { kana: "ひふやしろめがきいろくなること", romaji: "hifu ya shirome ga kiiroku naru koto" },
  "目が見えにくくなりました": { kana: "めがみえにくくなりました", romaji: "me ga mie nikuku nari mashi ta" },
  "目が黄色いと言われました": { kana: "めがきいろいといわれました", romaji: "me ga kiiroi to iwa re mashi ta" },
  "目にさす薬": { kana: "めにさすくすり", romaji: "me ni sasu kusuri" },
  "目に入れて使う薬": { kana: "めにいれてつかうくすり", romaji: "me ni ire te tsukau kusuri" },
  "目の前が暗くなって倒れそうでした": { kana: "めのまえがくらくなってたおれそうでした", romaji: "me no mae ga kuraku natsu te taore soo deshi ta" },
  "目の奥の網膜の血管が傷む病気": { kana: "めのおくのもうまくのけっかんがいたむびょうき", romaji: "me no oku no moomaku no kekkan ga itamu byooki" },
  "目薬を使っています": { kana: "めぐすりをつかっています", romaji: "megusuri o tsukatsu te i masu" },
  "盲腸の先に炎症が起きる病気": { kana: "もうちょうのさきにえんしょうがおきるびょうき", romaji: "moochoo no saki ni enshoo ga okiru byooki" },
  "真っ黒な便が出ました": { kana: "まっくろなびんがでました", romaji: "makkuro na bin ga de mashi ta" },
  "眠っている間に手術を受ける麻酔": { kana: "ねむっているあいだにしゅじゅつをうけるますい", romaji: "nemutsu te iru aida ni shujutsu o ukeru masui" },
  "磁石の力で体の中を写す検査": { kana: "じしゃくのちからでからだのなかをうつすけんさ", romaji: "jishaku no chikara de karada no naka o utsusu kensa" },
  "神経に沿って水ぶくれと痛みが出る病気": { kana: "しんけいにそってみずぶくれといたみがでるびょうき", romaji: "shinkee ni sotsu te mizubukure to itami ga deru byooki" },
  "神経の働きを確認する診察": { kana: "しんけいのはたらきをかくにんするしんさつ", romaji: "shinkee no hataraki o kakunin suru shinsatsu" },
  "突然息苦しくなりました": { kana: "とつぜんいきぐるしくなりました", romaji: "totsuzen ikigurushiku nari mashi ta" },
  "突然激しい頭痛がしました": { kana: "とつぜんはげしいずつうがしました", romaji: "totsuzen hageshii zutsuu ga shi mashi ta" },
  "筋肉に薬を注射すること": { kana: "きんにくにくすりをちゅうしゃすること", romaji: "kinniku ni kusuri o chuusha suru koto" },
  "粉になっている薬": { kana: "こなになっているくすり", romaji: "kona ni natsu te iru kusuri" },
  "細いカメラで気管支の中を見る検査": { kana: "ほそいかめらできかんしのなかをみるけんさ", romaji: "hosoi kamera de kikan shi no naka o miru kensa" },
  "細い管を入れて体の中を直接見る検査": { kana: "ほそいくだをいれてからだのなかをちょくせつみるけんさ", romaji: "hosoi kuda o ire te karada no naka o chokusetsu miru kensa" },
  "細い管を入れて尿を出すこと": { kana: "ほそいくだをいれてにょうをだすこと", romaji: "hosoi kuda o ire te nyoo o dasu koto" },
  "細菌をやっつける薬": { kana: "さいきんをやっつけるくすり", romaji: "saikin o yattsukeru kusuri" },
  "細菌を抑えたり退治したりする薬": { kana: "さいきんをおさえたりたいじしたりするくすり", romaji: "saikin o osae tari taiji shi tari suru kusuri" },
  "細菌を育てて種類を調べる検査": { kana: "さいきんをそだててしゅるいをしらべるけんさ", romaji: "saikin o sodate te shurui o shiraberu kensa" },
  "紹介状を書いてもらえますか": { kana: "しょうかいじょうをかいてもらえますか", romaji: "shookai joo o kai te morae masu ka" },
  "組織の一部を採って調べること": { kana: "そしきのいちぶをとってしらべること", romaji: "soshiki no ichibu o totsu te shiraberu koto" },
  "結核菌による感染症": { kana: "けっかくきんによるかんせんしょう", romaji: "kekkaku kin ni yoru kansen shoo" },
  "緊急度に応じて診療の順番を決めること": { kana: "きんきゅうどにおうじてしんりょうのじゅんばんをきめること", romaji: "kinkyuu do ni ooji te shinryoo no junban o kimeru koto" },
  "聴診器で体の音を聞く診察": { kana: "ちょうしんきでからだのおとをきくしんさつ", romaji: "chooshin ki de karada no oto o kiku shinsatsu" },
  "肛門からカメラを入れて大腸を見る検査": { kana: "こうもんからかめらをいれてだいちょうをみるけんさ", romaji: "koomon kara kamera o ire te daichoo o miru kensa" },
  "肝臓がうまく働いているか調べる血液検査": { kana: "かんぞうがうまくはたらいているかしらべるけつえきけんさ", romaji: "kanzoo ga umaku hatarai te iru ka shiraberu ketsueki kensa" },
  "肝臓のはたらきを調べる検査": { kana: "かんぞうのはたらきをしらべるけんさ", romaji: "kanzoo no hataraki o shiraberu kensa" },
  "肺から空気が漏れて胸にたまる状態": { kana: "はいからくうきがもれてむねにたまるじょうたい", romaji: "hai kara kuuki ga more te mune ni tamaru jootai" },
  "肺の中に炎症が起きる病気": { kana: "はいのなかにえんしょうがおきるびょうき", romaji: "hai no naka ni enshoo ga okiru byooki" },
  "肺の周りに水がたまっていると言われました": { kana: "はいのまわりにみずがたまっているといわれました", romaji: "hai no mawari ni mizu ga tamatsu te iru to iwa re mashi ta" },
  "肺の周りに水がたまること": { kana: "はいのまわりにみずがたまること", romaji: "hai no mawari ni mizu ga tamaru koto" },
  "肺の血管が詰まる病気": { kana: "はいのけっかんがつまるびょうき", romaji: "hai no kekkan ga tsumaru byooki" },
  "胃と腸に炎症が起きる病気": { kana: "いとちょうにえんしょうがおきるびょうき", romaji: "i to choo ni enshoo ga okiru byooki" },
  "胃の中にすみつく細菌": { kana: "いのなかにすみつくさいきん", romaji: "i no naka ni sumitsuku saikin" },
  "胃の内容物を吐くこと": { kana: "いのないようぶつをはくこと", romaji: "i no naiyoo butsu o haku koto" },
  "胃の粘膜に炎症が起きる病気": { kana: "いのねんまくにえんしょうがおきるびょうき", romaji: "i no nenmaku ni enshoo ga okiru byooki" },
  "胃や腸から血が出ること": { kana: "いやちょうからちがでること", romaji: "i ya choo kara chi ga deru koto" },
  "胃カメラを受けます": { kana: "いかめらをうけます", romaji: "i kamera o uke masu" },
  "胆のうに炎症が起きる病気": { kana: "たんのうにえんしょうがおきるびょうき", romaji: "tannoo ni enshoo ga okiru byooki" },
  "胆のうに石ができる病気": { kana: "たんのうにいしができるびょうき", romaji: "tannoo ni ishi ga dekiru byooki" },
  "背中まで痛みが広がります": { kana: "せなかまでいたみがひろがります", romaji: "senaka made itami ga hirogari masu" },
  "胸が痛い状態": { kana: "むねがいたいじょうたい", romaji: "mune ga itai jootai" },
  "胸が締め付けられる感じがします": { kana: "むねがしめつけられるかんじがします", romaji: "mune ga shimetsuke rareru kanji ga shi masu" },
  "胸にシールを貼られました": { kana: "むねにしーるをはられました", romaji: "mune ni shiiru o hara re mashi ta" },
  "胸の写真を撮りました": { kana: "むねのしゃしんをとりました", romaji: "mune no shashin o tori mashi ta" },
  "胸の音を聞いてもらいました": { kana: "むねのおとをきいてもらいました", romaji: "mune no oto o kii te morai mashi ta" },
  "脂っこいものを食べた後、右上腹部が痛みます": { kana: "あぶらっこいものをたべたあと、みぎうえふくぶがいたみます", romaji: "aburakkoi mono o tabe ta ato、 migiue fukubu ga itami masu" },
  "脈がばらばらで動悸がします": { kana: "みゃくがばらばらでどうきがします", romaji: "myaku ga barabara de dooki ga shi masu" },
  "脈が速い状態": { kana: "みゃくがはやいじょうたい", romaji: "myaku ga hayai jootai" },
  "脈が遅い状態": { kana: "みゃくがおそいじょうたい", romaji: "myaku ga osoi jootai" },
  "脈の数": { kana: "みゃくのかず", romaji: "myaku no kazu" },
  "脳の血管が破れる病気": { kana: "のうのけっかんがやぶれるびょうき", romaji: "noo no kekkan ga yabureru byooki" },
  "脳の血管が詰まる病気": { kana: "のうのけっかんがつまるびょうき", romaji: "noo no kekkan ga tsumaru byooki" },
  "腎臓がうまく働いているか調べる検査": { kana: "じんぞうがうまくはたらいているかしらべるけんさ", romaji: "jinzoo ga umaku hatarai te iru ka shiraberu kensa" },
  "腎臓のはたらきを調べる検査": { kana: "じんぞうのはたらきをしらべるけんさ", romaji: "jinzoo no hataraki o shiraberu kensa" },
  "腕から血を採って調べる検査": { kana: "うでからちをとってしらべるけんさ", romaji: "ude kara chi o totsu te shiraberu kensa" },
  "腕から血を採ること": { kana: "うでからちをとること", romaji: "ude kara chi o toru koto" },
  "腕などの血管に入れる点滴の管": { kana: "うでなどのけっかんにいれるてんてきのくだ", romaji: "ude nado no kekkan ni ireru tenteki no kuda" },
  "腕の血管から水分や薬を入れること": { kana: "うでのけっかんからすいぶんやくすりをいれること", romaji: "ude no kekkan kara suibun ya kusuri o ireru koto" },
  "腰から細い針を入れて脳脊髄液を調べる検査": { kana: "こしからほそいはりをいれてのうせきずいえきをしらべるけんさ", romaji: "koshi kara hosoi hari o ire te noo sekizui eki o shiraberu kensa" },
  "腰から針を刺して髄液を調べる検査": { kana: "こしからはりをさしてずいえきをしらべるけんさ", romaji: "koshi kara hari o sashi te zuieki o shiraberu kensa" },
  "腰が痛くて曲げられません": { kana: "こしがいたくてまげられません", romaji: "koshi ga itaku te mage rare mase n" },
  "膵臓に炎症が起きる病気": { kana: "すいぞうにえんしょうがおきるびょうき", romaji: "suizoo ni enshoo ga okiru byooki" },
  "薬でアレルギーが出ること": { kana: "くすりであれるぎーがでること", romaji: "kusuri de arerugii ga deru koto" },
  "薬で発疹が出たことがあります": { kana: "くすりではっしんがでたことがあります", romaji: "kusuri de hasshin ga de ta koto ga ari masu" },
  "薬によって起こる望ましくない症状": { kana: "くすりによっておこるのぞましくないしょうじょう", romaji: "kusuri ni yotsu te okoru nozomashiku nai shoojoo" },
  "薬を毎日飲めない日があります": { kana: "くすりをまいにちのめないひがあります", romaji: "kusuri o mainichi nome nai hi ga ari masu" },
  "薬を飲んだ後、息が苦しくなりました": { kana: "くすりをのんだあと、いきがくるしくなりました", romaji: "kusuri o non da ato、 iki ga kurushiku nari mashi ta" },
  "薬を飲んでから気持ちが悪いです": { kana: "くすりをのんでからきもちがわるいです", romaji: "kusuri o non de kara kimochi ga warui desu" },
  "薬同士の影響で効き方や副作用が変わること": { kana: "くすりどうしのえいきょうでききかたやふくさようがかわること", romaji: "kusuri dooshi no eekyoo de kiki kata ya fuku sayoo ga kawaru koto" },
  "薬局で薬をもらうための紙": { kana: "やっきょくでくすりをもらうためのかみ", romaji: "yakkyoku de kusuri o morau tame no kami" },
  "蚊に刺されて起こるウイルスの病気": { kana: "かにさされておこるういるすのびょうき", romaji: "ka ni sasa re te okoru uirusu no byooki" },
  "血が出ること": { kana: "ちがでること", romaji: "chi ga deru koto" },
  "血が固まりにくくなる薬": { kana: "ちがかたまりにくくなるくすり", romaji: "chi ga katamari nikuku naru kusuri" },
  "血が止まりません": { kana: "ちがとまりません", romaji: "chi ga tomari mase n" },
  "血の流れが悪くなって危険な状態": { kana: "ちのながれがわるくなってきけんなじょうたい", romaji: "chi no nagare ga waruku natsu te kiken na jootai" },
  "血を入れる治療が必要ですか": { kana: "ちをいれるちりょうがひつようですか", romaji: "chi o ireru chiryoo ga hitsuyoo desu ka" },
  "血を吐きました": { kana: "ちをはきました", romaji: "chi o haki mashi ta" },
  "血を吐くこと": { kana: "ちをはくこと", romaji: "chi o haku koto" },
  "血を固まりにくくする薬を飲んでいます": { kana: "ちをかたまりにくくするくすりをのんでいます", romaji: "chi o katamari nikuku suru kusuri o non de i masu" },
  "血を止めるはたらきをする血液の成分": { kana: "ちをとめるはたらきをするけつえきのせいぶん", romaji: "chi o tomeru hataraki o suru ketsueki no seebun" },
  "血圧が高いと言われています": { kana: "けつあつがたかいといわれています", romaji: "ketsuatsu ga takai to iwa re te i masu" },
  "血圧が高いと言われました": { kana: "けつあつがたかいといわれました", romaji: "ketsuatsu ga takai to iwa re mashi ta" },
  "血圧が高い状態が続く病気": { kana: "けつあつがたかいじょうたいがつづくびょうき", romaji: "ketsuatsu ga takai jootai ga tsuzuku byooki" },
  "血圧の薬を飲んでいます": { kana: "けつあつのくすりをのんでいます", romaji: "ketsuatsu no kusuri o non de i masu" },
  "血圧を下げる薬": { kana: "けつあつをさげるくすり", romaji: "ketsuatsu o sageru kusuri" },
  "血小板が集まるのを抑える薬": { kana: "けつしょうばんがあつまるのをおさえるくすり", romaji: "ketsu shooban ga atsumaru no o osaeru kusuri" },
  "血液が固まりにくくなる薬": { kana: "けつえきがかたまりにくくなるくすり", romaji: "ketsueki ga katamari nikuku naru kusuri" },
  "血液の中に細菌がいるか調べる検査": { kana: "けつえきのなかにさいきんがいるかしらべるけんさ", romaji: "ketsueki no naka ni saikin ga iru ka shiraberu kensa" },
  "血液の中の糖分が多くなる病気": { kana: "けつえきのなかのとうぶんがおおくなるびょうき", romaji: "ketsueki no naka no toobun ga ooku naru byooki" },
  "血液の中の糖分の量": { kana: "けつえきのなかのとうぶんのりょう", romaji: "ketsueki no naka no toobun no ryoo" },
  "血液の中の酸素の量": { kana: "けつえきのなかのさんそのりょう", romaji: "ketsueki no naka no sanso no ryoo" },
  "血液の細胞の数を調べる検査": { kana: "けつえきのさいぼうのかずをしらべるけんさ", romaji: "ketsueki no saiboo no kazu o shiraberu kensa" },
  "血液を体に入れる治療": { kana: "けつえきをからだにいれるちりょう", romaji: "ketsueki o karada ni ireru chiryoo" },
  "血液中の糖分の量": { kana: "けつえきちゅうのとうぶんのりょう", romaji: "ketsueki chuu no toobun no ryoo" },
  "血液中の酸素や二酸化炭素を調べる検査": { kana: "けつえきちゅうのさんそやにさんかたんそをしらべるけんさ", romaji: "ketsueki chuu no sanso ya ni sanka tanso o shiraberu kensa" },
  "血管に薬を注射すること": { kana: "けっかんにくすりをちゅうしゃすること", romaji: "kekkan ni kusuri o chuusha suru koto" },
  "血糖が高いと言われました": { kana: "けっとうがたかいといわれました", romaji: "kettoo ga takai to iwa re mashi ta" },
  "血糖を下げるホルモンの注射薬": { kana: "けっとうをさげるほるもんのちゅうしゃやく", romaji: "kettoo o sageru horumon no chuusha yaku" },
  "血糖値が下がりすぎた状態": { kana: "けっとうちがさがりすぎたじょうたい", romaji: "kettoo chi ga sagari sugi ta jootai" },
  "血糖値が高いと言われています": { kana: "けっとうちがたかいといわれています", romaji: "kettoo chi ga takai to iwa re te i masu" },
  "血糖値を下げる薬": { kana: "けっとうちをさげるくすり", romaji: "kettoo chi o sageru kusuri" },
  "視力が落ちた気がします": { kana: "しりょくがおちたきがします", romaji: "shiryoku ga ochi ta ki ga shi masu" },
  "言葉がうまく出ません": { kana: "ことばがうまくでません", romaji: "kotoba ga umaku de mase n" },
  "詰まった血管の血の塊を溶かす薬": { kana: "つまったけっかんのちのかたまりをとかすくすり", romaji: "tsumatsu ta kekkan no chi no katamari o tokasu kusuri" },
  "赤いぶつぶつが出ました": { kana: "あかいぶつぶつがでました", romaji: "akai butsubutsu ga de mashi ta" },
  "超音波で心臓の動きや弁を調べる検査": { kana: "ちょうおんぱでしんぞうのうごきやべんをしらべるけんさ", romaji: "choo onpa de shinzoo no ugoki ya ben o shiraberu kensa" },
  "超音波で心臓の動きを見る検査": { kana: "ちょうおんぱでしんぞうのうごきをみるけんさ", romaji: "choo onpa de shinzoo no ugoki o miru kensa" },
  "超音波を使って体の中を見る検査": { kana: "ちょうおんぱをつかってからだのなかをみるけんさ", romaji: "choo onpa o tsukatsu te karada no naka o miru kensa" },
  "足がはれています": { kana: "あしがはれています", romaji: "ashi ga hare te i masu" },
  "足がむくんでいます": { kana: "あしがむくんでいます", romaji: "ashi ga mukun de i masu" },
  "足がむくんで靴がきついです": { kana: "あしがむくんでくつがきついです", romaji: "ashi ga mukun de kutsu ga kitsui desu" },
  "足りない血液を補うこと": { kana: "たりないけつえきをおぎなうこと", romaji: "tari nai ketsueki o oginau koto" },
  "転んで腕を骨折しました": { kana: "ころんでうでをこっせつしました", romaji: "koron de ude o kossetsu shi mashi ta" },
  "退院後の生活や支援を準備すること": { kana: "たいいんごのせいかつやしえんをじゅんびすること", romaji: "taiin go no seekatsu ya shien o junbi suru koto" },
  "通って受診するところ": { kana: "とおってじゅしんするところ", romaji: "tootsu te jushin suru tokoro" },
  "造影剤を使って体の中を詳しく見るCT検査": { kana: "ぞうえいざいをつかってからだのなかをくわしくみるCTけんさ", romaji: "zooee zai o tsukatsu te karada no naka o kuwashiku miru CT kensa" },
  "運動しながら心臓の状態を調べる検査": { kana: "うんどうしながらしんぞうのじょうたいをしらべるけんさ", romaji: "undoo shi nagara shinzoo no jootai o shiraberu kensa" },
  "酸素を吸うためのマスク": { kana: "さんそをすうためのますく", romaji: "sanso o suu tame no masuku" },
  "重症の方を24時間見守る部屋": { kana: "じゅうしょうのほうを24じかんみまもるへや", romaji: "juushoo no hoo o 24 jikan mimamoru heya" },
  "長年の喫煙などで息が苦しくなる病気": { kana: "ながねんのきつえんなどでいきがくるしくなるびょうき", romaji: "naganen no kitsuen nado de iki ga kurushiku naru byooki" },
  "関節が痛みます": { kana: "かんせつがいたみます", romaji: "kansetsu ga itami masu" },
  "階段で息が上がります": { kana: "かいだんでいきがあがります", romaji: "kaidan de iki ga agari masu" },
  "音がどのくらい聞こえるか調べる検査": { kana: "おとがどのくらいきこえるかしらべるけんさ", romaji: "oto ga dono kurai kikoeru ka shiraberu kensa" },
  "音波で体の中を見る検査": { kana: "おんぱでからだのなかをみるけんさ", romaji: "onpa de karada no naka o miru kensa" },
  "頭がふらふらする感じ": { kana: "あたまがふらふらするかんじ", romaji: "atama ga furafura suru kanji" },
  "頭がズキズキします": { kana: "あたまがずきずきします", romaji: "atama ga zukizuki shi masu" },
  "頭が痛い状態": { kana: "あたまがいたいじょうたい", romaji: "atama ga itai jootai" },
  "頭の片側が脈打つように痛くなる病気": { kana: "あたまのかたがわがみゃくうつようにいたくなるびょうき", romaji: "atama no katagawa ga myakuutsu yoo ni itaku naru byooki" },
  "食べたい気持ちがなくなること": { kana: "たべたいきもちがなくなること", romaji: "tabe tai kimochi ga nakunaru koto" },
  "食べ物でアレルギーが出ること": { kana: "たべものであれるぎーがでること", romaji: "tabemono de arerugii ga deru koto" },
  "食べ物や飲み物を飲み込みにくい状態": { kana: "たべものやのみものをのみこみにくいじょうたい", romaji: "tabemono ya nomimono o nomikomi nikui jootai" },
  "食事を変えていないのに体重が減りました": { kana: "しょくじをかえていないのにたいじゅうがへりました", romaji: "shokuji o kae te i nai no ni taijuu ga heri mashi ta" },
  "食欲がなくて、あまり食べられません": { kana: "しょくよくがなくて、あまりたべられません", romaji: "shokuyoku ga naku te、 amari tabe rare mase n" },
  "飲み込むときの痛み": { kana: "のみこむときのいたみ", romaji: "nomikomu toki no itami" },
  "飲み込むとむせます": { kana: "のみこむとむせます", romaji: "nomikomu to muse masu" },
  "飲み込むと喉が痛いです": { kana: "のみこむとのどがいたいです", romaji: "nomikomu to nodo ga itai desu" },
  "飲んでいる薬を記録するノート": { kana: "のんでいるくすりをきろくするのーと", romaji: "non de iru kusuri o kiroku suru nooto" },
  "飲んでいる薬を記録する手帳": { kana: "のんでいるくすりをきろくするてちょう", romaji: "non de iru kusuri o kiroku suru techoo" },
  "首やわきの下のぐりぐりが腫れること": { kana: "くびやわきのしたのぐりぐりがはれること", romaji: "kubi ya waki no shita no guriguri ga hareru koto" },
  "骨が折れること": { kana: "ほねがおれること", romaji: "hone ga oreru koto" },
  "骨の強さを調べる検査": { kana: "ほねのつよさをしらべるけんさ", romaji: "hone no tsuyo sa o shiraberu kensa" },
  "高熱と関節痛が続きます": { kana: "こうねつとかんせつつうがつづきます", romaji: "koonetsu to kansetsu tsuu ga tsuzuki masu" },
  "黄色い痰が出ます": { kana: "きいろいたんがでます", romaji: "kiiroi tan ga de masu" },
  "黒い便が出ました": { kana: "くろいびんがでました", romaji: "kuroi bin ga de mashi ta" },
  "黒くてタールのような便": { kana: "くろくてたーるのようなびん", romaji: "kuroku te taaru no yoo na bin" },
  "鼻が詰まって息がしにくいです": { kana: "はながつまっていきがしにくいです", romaji: "hana ga tsumatsu te iki ga shi nikui desu" },
  "鼻が詰まること": { kana: "はながつまること", romaji: "hana ga tsumaru koto" },
  "鼻に入れて使う薬": { kana: "はなにいれてつかうくすり", romaji: "hana ni ire te tsukau kusuri" },
  "鼻やのどにウイルスがつく病気": { kana: "はなやのどにういるすがつくびょうき", romaji: "hana ya nodo ni uirusu ga tsuku byooki" },
  "鼻や口から酸素を吸ってもらうこと": { kana: "はなやくちからさんそをすってもらうこと", romaji: "hana ya kuchi kara sanso o sutsu te morau koto" },
  "鼻水が出ること": { kana: "はなみずがでること", romaji: "hanamizu ga deru koto" },
};

export function medicalRegisterReadingFor(japanese: string): MedicalRegisterReading {
  const reading = MEDICAL_REGISTER_READINGS[japanese];
  if (!reading) throw new Error(`Missing Medical register reading: ${japanese}`);
  return reading;
}

export const MEDICAL_REGISTER_SUPPORT_STATUS = 'draft' as const;
